/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */

module Decoder4 (
    output out_0,
    output out_1,
    output out_2,
    output out_3,
    output out_4,
    output out_5,
    output out_6,
    output out_7,
    output out_8,
    output out_9,
    output out_10,
    output out_11,
    output out_12,
    output out_13,
    output out_14,
    output out_15,
    input [3:0] sel
);
    assign out_0 = (sel == 4'h0)? 1'b1 : 1'b0;
    assign out_1 = (sel == 4'h1)? 1'b1 : 1'b0;
    assign out_2 = (sel == 4'h2)? 1'b1 : 1'b0;
    assign out_3 = (sel == 4'h3)? 1'b1 : 1'b0;
    assign out_4 = (sel == 4'h4)? 1'b1 : 1'b0;
    assign out_5 = (sel == 4'h5)? 1'b1 : 1'b0;
    assign out_6 = (sel == 4'h6)? 1'b1 : 1'b0;
    assign out_7 = (sel == 4'h7)? 1'b1 : 1'b0;
    assign out_8 = (sel == 4'h8)? 1'b1 : 1'b0;
    assign out_9 = (sel == 4'h9)? 1'b1 : 1'b0;
    assign out_10 = (sel == 4'ha)? 1'b1 : 1'b0;
    assign out_11 = (sel == 4'hb)? 1'b1 : 1'b0;
    assign out_12 = (sel == 4'hc)? 1'b1 : 1'b0;
    assign out_13 = (sel == 4'hd)? 1'b1 : 1'b0;
    assign out_14 = (sel == 4'he)? 1'b1 : 1'b0;
    assign out_15 = (sel == 4'hf)? 1'b1 : 1'b0;
endmodule


module \16_BitDecoderWithEnablePin  (
  input EN,
  input [3:0] Sel_4Bit,
  output Q0,
  output Q1,
  output Q2,
  output Q3,
  output Q4,
  output Q5,
  output Q6,
  output Q7,
  output Q8,
  output Q9,
  output Q10,
  output Q11,
  output Q12,
  output Q13,
  output Q14,
  output Q15
);
  wire s0;
  wire s1;
  wire s2;
  wire s3;
  wire s4;
  wire s5;
  wire s6;
  wire s7;
  wire s8;
  wire s9;
  wire s10;
  wire s11;
  wire s12;
  wire s13;
  wire s14;
  wire s15;
  Decoder4 Decoder4_i0 (
    .sel( Sel_4Bit ),
    .out_0( s0 ),
    .out_1( s1 ),
    .out_2( s2 ),
    .out_3( s3 ),
    .out_4( s4 ),
    .out_5( s5 ),
    .out_6( s6 ),
    .out_7( s7 ),
    .out_8( s8 ),
    .out_9( s9 ),
    .out_10( s10 ),
    .out_11( s11 ),
    .out_12( s12 ),
    .out_13( s13 ),
    .out_14( s14 ),
    .out_15( s15 )
  );
  assign Q0 = (EN & s0);
  assign Q1 = (EN & s1);
  assign Q2 = (EN & s2);
  assign Q3 = (EN & s3);
  assign Q4 = (EN & s4);
  assign Q5 = (EN & s5);
  assign Q6 = (EN & s6);
  assign Q7 = (EN & s7);
  assign Q8 = (EN & s8);
  assign Q9 = (EN & s9);
  assign Q10 = (EN & s10);
  assign Q11 = (EN & s11);
  assign Q12 = (EN & s12);
  assign Q13 = (EN & s13);
  assign Q14 = (EN & s14);
  assign Q15 = (EN & s15);
endmodule
module DIG_D_FF_Nbit
#(
    parameter Bits = 2,
    parameter Default = 0
)
(
   input [(Bits-1):0] D,
   input C,
   output [(Bits-1):0] Q,
   output [(Bits-1):0] \~Q
);
    reg [(Bits-1):0] state;

    assign Q = state;
    assign \~Q = ~state;

    always @ (posedge C) begin
        state <= D;
    end

    initial begin
        state = Default;
    end
endmodule

module DIG_D_FF_1bit
#(
    parameter Default = 0
)
(
   input D,
   input C,
   output Q,
   output \~Q
);
    reg state;

    assign Q = state;
    assign \~Q = ~state;

    always @ (posedge C) begin
        state <= D;
    end

    initial begin
        state = Default;
    end
endmodule


module ALU_RegCtrl (
  input \IsEn?_Decoder ,
  input CLK,
  input \0x0 ,
  input \0x1 ,
  input \0x2 ,
  input \0x3 ,
  input \0x4 ,
  input \0x5 ,
  input \0x6 ,
  input \0x7 ,
  input \0x8 ,
  input \0x9 ,
  input \0xA ,
  input \0xB ,
  input \0xC ,
  input \0xD ,
  input \0xE ,
  input \0xF ,
  input [3:0] OPCODE_IN,
  output Q_0,
  output Q_1,
  output Q_2,
  output Q_3,
  output Q_4,
  output Q_5,
  output Q_6,
  output Q_7,
  output Q_8,
  output Q_9,
  output Q_A,
  output Q_B,
  output Q_C,
  output Q_D,
  output Q_E,
  output Q_F,
  output RST,
  output [3:0] OPCODE_OUT
);
  wire RST_temp;
  wire s0;
  wire s1;
  wire s2;
  wire s3;
  wire s4;
  wire s5;
  wire s6;
  wire s7;
  wire s8;
  wire s9;
  wire s10;
  wire s11;
  wire s12;
  wire s13;
  wire s14;
  wire s15;
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i0 (
    .D( \0x0  ),
    .C( CLK ),
    .Q( s0 )
  );
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i1 (
    .D( \0x1  ),
    .C( CLK ),
    .Q( s1 )
  );
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i2 (
    .D( \0x2  ),
    .C( CLK ),
    .Q( s2 )
  );
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i3 (
    .D( \0x3  ),
    .C( CLK ),
    .Q( s3 )
  );
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i4 (
    .D( \0x4  ),
    .C( CLK ),
    .Q( s4 )
  );
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i5 (
    .D( \0x5  ),
    .C( CLK ),
    .Q( s5 )
  );
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i6 (
    .D( \0x6  ),
    .C( CLK ),
    .Q( s6 )
  );
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i7 (
    .D( \0x7  ),
    .C( CLK ),
    .Q( s7 )
  );
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i8 (
    .D( \0x8  ),
    .C( CLK ),
    .Q( s8 )
  );
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i9 (
    .D( \0x9  ),
    .C( CLK ),
    .Q( s9 )
  );
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i10 (
    .D( \0xA  ),
    .C( CLK ),
    .Q( s10 )
  );
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i11 (
    .D( \0xB  ),
    .C( CLK ),
    .Q( s11 )
  );
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i12 (
    .D( \0xC  ),
    .C( CLK ),
    .Q( s12 )
  );
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i13 (
    .D( \0xD  ),
    .C( CLK ),
    .Q( s13 )
  );
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i14 (
    .D( \0xE  ),
    .C( CLK ),
    .Q( s14 )
  );
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i15 (
    .D( \0xF  ),
    .C( CLK ),
    .Q( s15 )
  );
  assign RST_temp = ~ \IsEn?_Decoder ;
  DIG_D_FF_Nbit #(
    .Bits(4),
    .Default(0)
  )
  DIG_D_FF_Nbit_i16 (
    .D( OPCODE_IN ),
    .C( CLK ),
    .Q( OPCODE_OUT )
  );
  assign Q_0 = (RST_temp | s0);
  assign Q_1 = (RST_temp | s1);
  assign Q_2 = (RST_temp | s2);
  assign Q_3 = (RST_temp | s3);
  assign Q_4 = (RST_temp | s4);
  assign Q_5 = (RST_temp | s5);
  assign Q_6 = (RST_temp | s6);
  assign Q_7 = (RST_temp | s7);
  assign Q_8 = (RST_temp | s8);
  assign Q_9 = (RST_temp | s9);
  assign Q_A = (RST_temp | s10);
  assign Q_B = (RST_temp | s11);
  assign Q_C = (RST_temp | s12);
  assign Q_D = (RST_temp | s13);
  assign Q_E = (RST_temp | s14);
  assign Q_F = (RST_temp | s15);
  assign RST = RST_temp;
endmodule

module ALU_RegRST (
  input [15:0] D,
  input RST,
  output [15:0] Q
);
  wire s0;
  assign s0 = ~ RST;
  assign Q[0] = (s0 & D[0]);
  assign Q[1] = (s0 & D[1]);
  assign Q[2] = (s0 & D[2]);
  assign Q[3] = (s0 & D[3]);
  assign Q[4] = (s0 & D[4]);
  assign Q[5] = (s0 & D[5]);
  assign Q[6] = (s0 & D[6]);
  assign Q[7] = (s0 & D[7]);
  assign Q[8] = (s0 & D[8]);
  assign Q[9] = (s0 & D[9]);
  assign Q[10] = (s0 & D[10]);
  assign Q[11] = (s0 & D[11]);
  assign Q[12] = (s0 & D[12]);
  assign Q[13] = (s0 & D[13]);
  assign Q[14] = (s0 & D[14]);
  assign Q[15] = (s0 & D[15]);
endmodule
module PriorityEncoder2 (
    input in0,
    input in1,
    input in2,
    input in3,
    output reg [1:0] num,
    output any
);
    always @ (*) begin
        if (in3 == 1'b1)
            num = 2'h3;
        else if (in2 == 1'b1)
            num = 2'h2;
        else if (in1 == 1'b1)
            num = 2'h1;
        else 
            num = 2'h0;
    end

    assign any = in0 | in1 | in2 | in3;
endmodule


module DIG_Register
(
    input C,
    input en,
    input D,
    output Q
);

    reg  state = 'h0;

    assign Q = state;

    always @ (posedge C) begin
        if (en)
            state <= D;
   end
endmodule

module \16_BitRegister  (
  input D,
  input EN,
  input CLK,
  output Q0,
  output Q1,
  output Q2,
  output Q3,
  output Q4,
  output Q5,
  output Q6,
  output Q7,
  output Q8,
  output Q9,
  output Q10,
  output Q11,
  output Q12,
  output Q13,
  output Q14,
  output Q15
);
  wire s0;
  wire s1;
  wire s2;
  wire s3;
  wire s4;
  wire s5;
  wire s6;
  wire s7;
  wire s8;
  wire s9;
  wire s10;
  wire s11;
  wire s12;
  wire s13;
  wire s14;
  wire s15;
  assign s0 = D[0];
  assign s4 = D[1];
  assign s8 = D[2];
  assign s12 = D[3];
  assign s1 = D[4];
  assign s5 = D[5];
  assign s9 = D[6];
  assign s13 = D[7];
  assign s2 = D[8];
  assign s6 = D[9];
  assign s10 = D[10];
  assign s14 = D[11];
  assign s3 = D[12];
  assign s7 = D[13];
  assign s11 = D[14];
  assign s15 = D[15];
  // reg1
  DIG_Register DIG_Register_i0 (
    .D( s0 ),
    .C( CLK ),
    .en( EN ),
    .Q( Q0 )
  );
  // reg5
  DIG_Register DIG_Register_i1 (
    .D( s1 ),
    .C( CLK ),
    .en( EN ),
    .Q( Q4 )
  );
  // reg9
  DIG_Register DIG_Register_i2 (
    .D( s2 ),
    .C( CLK ),
    .en( EN ),
    .Q( Q8 )
  );
  // reg13
  DIG_Register DIG_Register_i3 (
    .D( s3 ),
    .C( CLK ),
    .en( EN ),
    .Q( Q12 )
  );
  // reg2
  DIG_Register DIG_Register_i4 (
    .D( s4 ),
    .C( CLK ),
    .en( EN ),
    .Q( Q1 )
  );
  // reg6
  DIG_Register DIG_Register_i5 (
    .D( s5 ),
    .C( CLK ),
    .en( EN ),
    .Q( Q5 )
  );
  // reg10
  DIG_Register DIG_Register_i6 (
    .D( s6 ),
    .C( CLK ),
    .en( EN ),
    .Q( Q9 )
  );
  // reg14
  DIG_Register DIG_Register_i7 (
    .D( s7 ),
    .C( CLK ),
    .en( EN ),
    .Q( Q13 )
  );
  // reg3
  DIG_Register DIG_Register_i8 (
    .D( s8 ),
    .C( CLK ),
    .en( EN ),
    .Q( Q2 )
  );
  // reg7
  DIG_Register DIG_Register_i9 (
    .D( s9 ),
    .C( CLK ),
    .en( EN ),
    .Q( Q6 )
  );
  // reg11
  DIG_Register DIG_Register_i10 (
    .D( s10 ),
    .C( CLK ),
    .en( EN ),
    .Q( Q10 )
  );
  // reg15
  DIG_Register DIG_Register_i11 (
    .D( s11 ),
    .C( CLK ),
    .en( EN ),
    .Q( Q14 )
  );
  // reg4
  DIG_Register DIG_Register_i12 (
    .D( s12 ),
    .C( CLK ),
    .en( EN ),
    .Q( Q3 )
  );
  // reg8
  DIG_Register DIG_Register_i13 (
    .D( s13 ),
    .C( CLK ),
    .en( EN ),
    .Q( Q7 )
  );
  // reg12
  DIG_Register DIG_Register_i14 (
    .D( s14 ),
    .C( CLK ),
    .en( EN ),
    .Q( Q11 )
  );
  // reg16
  DIG_Register DIG_Register_i15 (
    .D( s15 ),
    .C( CLK ),
    .en( EN ),
    .Q( Q15 )
  );
endmodule

module Mux_4x1
(
    input [1:0] sel,
    input in_0,
    input in_1,
    input in_2,
    input in_3,
    output reg out
);
    always @ (*) begin
        case (sel)
            2'h0: out = in_0;
            2'h1: out = in_1;
            2'h2: out = in_2;
            2'h3: out = in_3;
            default:
                out = 'h0;
        endcase
    end
endmodule


module DIG_Register_BUS #(
    parameter Bits = 1
)
(
    input C,
    input en,
    input [(Bits - 1):0]D,
    output [(Bits - 1):0]Q
);

    reg [(Bits - 1):0] state = 'h0;

    assign Q = state;

    always @ (posedge C) begin
        if (en)
            state <= D;
   end
endmodule
module DIG_Add
#(
    parameter Bits = 1
)
(
    input [(Bits-1):0] a,
    input [(Bits-1):0] b,
    input c_i,
    output [(Bits - 1):0] s,
    output c_o
);
   wire [Bits:0] temp;

   assign temp = a + b + c_i;
   assign s = temp [(Bits-1):0];
   assign c_o = temp[Bits];
endmodule



module DIG_Sub #(
    parameter Bits = 2
)
(
    input [(Bits-1):0] a,
    input [(Bits-1):0] b,
    input c_i,
    output [(Bits-1):0] s,
    output c_o
);
    wire [Bits:0] temp;

    assign temp = a - b - c_i;
    assign s = temp[(Bits-1):0];
    assign c_o = temp[Bits];
endmodule


module DIG_Mul_signed #(
    parameter Bits = 1
)
(
    
      input signed [(Bits-1):0] a,
      input signed [(Bits-1):0] b,
      output signed [(Bits*2-1):0] mul
    
);
    assign mul = a * b;
endmodule


module \16_BitAndOP  (
  input [15:0] A,
  input [15:0] B,
  output [15:0] Q
);
  assign Q[0] = (A[0] & B[0]);
  assign Q[1] = (A[1] & B[1]);
  assign Q[2] = (A[2] & B[2]);
  assign Q[3] = (A[3] & B[3]);
  assign Q[4] = (A[4] & B[4]);
  assign Q[5] = (A[5] & B[5]);
  assign Q[6] = (A[6] & B[6]);
  assign Q[7] = (A[7] & B[7]);
  assign Q[8] = (A[8] & B[8]);
  assign Q[9] = (A[9] & B[9]);
  assign Q[10] = (A[10] & B[10]);
  assign Q[11] = (A[11] & B[11]);
  assign Q[12] = (A[12] & B[12]);
  assign Q[13] = (A[13] & B[13]);
  assign Q[14] = (A[14] & B[14]);
  assign Q[15] = (A[15] & B[15]);
endmodule

module \16_BitXorOP  (
  input [15:0] A,
  input [15:0] B,
  output [15:0] Q
);
  assign Q[0] = (A[0] ^ B[0]);
  assign Q[1] = (A[1] ^ B[1]);
  assign Q[2] = (A[2] ^ B[2]);
  assign Q[3] = (A[3] ^ B[3]);
  assign Q[4] = (A[4] ^ B[4]);
  assign Q[5] = (A[5] ^ B[5]);
  assign Q[6] = (A[6] ^ B[6]);
  assign Q[7] = (A[7] ^ B[7]);
  assign Q[8] = (A[8] ^ B[8]);
  assign Q[9] = (A[9] ^ B[9]);
  assign Q[10] = (A[10] ^ B[10]);
  assign Q[11] = (A[11] ^ B[11]);
  assign Q[12] = (A[12] ^ B[12]);
  assign Q[13] = (A[13] ^ B[13]);
  assign Q[14] = (A[14] ^ B[14]);
  assign Q[15] = (A[15] ^ B[15]);
endmodule

module \16_BitOrOP  (
  input [15:0] A,
  input [15:0] B,
  output [15:0] Q
);
  assign Q[0] = (A[0] | B[0]);
  assign Q[1] = (A[1] | B[1]);
  assign Q[2] = (A[2] | B[2]);
  assign Q[3] = (A[3] | B[3]);
  assign Q[4] = (A[4] | B[4]);
  assign Q[5] = (A[5] | B[5]);
  assign Q[6] = (A[6] | B[6]);
  assign Q[7] = (A[7] | B[7]);
  assign Q[8] = (A[8] | B[8]);
  assign Q[9] = (A[9] | B[9]);
  assign Q[10] = (A[10] | B[10]);
  assign Q[11] = (A[11] | B[11]);
  assign Q[12] = (A[12] | B[12]);
  assign Q[13] = (A[13] | B[13]);
  assign Q[14] = (A[14] | B[14]);
  assign Q[15] = (A[15] | B[15]);
endmodule

module \16_BitNotOP  (
  input [15:0] D,
  output [15:0] Q
);
  assign Q[0] = ~ D[0];
  assign Q[1] = ~ D[1];
  assign Q[2] = ~ D[2];
  assign Q[3] = ~ D[3];
  assign Q[4] = ~ D[4];
  assign Q[5] = ~ D[5];
  assign Q[6] = ~ D[6];
  assign Q[7] = ~ D[7];
  assign Q[8] = ~ D[8];
  assign Q[9] = ~ D[9];
  assign Q[10] = ~ D[10];
  assign Q[11] = ~ D[11];
  assign Q[12] = ~ D[12];
  assign Q[13] = ~ D[13];
  assign Q[14] = ~ D[14];
  assign Q[15] = ~ D[15];
endmodule

module CompSigned #(
    parameter Bits = 1
)
(
    input [(Bits -1):0] a,
    input [(Bits -1):0] b,
    output \> ,
    output \= ,
    output \<
);
    assign \> = $signed(a) > $signed(b);
    assign \= = $signed(a) == $signed(b);
    assign \< = $signed(a) < $signed(b);
endmodule


module CompUnsigned #(
    parameter Bits = 1
)
(
    input [(Bits -1):0] a,
    input [(Bits -1):0] b,
    output \> ,
    output \= ,
    output \<
);
    assign \> = a > b;
    assign \= = a == b;
    assign \< = a < b;
endmodule


module Mux_4x1_NBits #(
    parameter Bits = 2
)
(
    input [1:0] sel,
    input [(Bits - 1):0] in_0,
    input [(Bits - 1):0] in_1,
    input [(Bits - 1):0] in_2,
    input [(Bits - 1):0] in_3,
    output reg [(Bits - 1):0] out
);
    always @ (*) begin
        case (sel)
            2'h0: out = in_0;
            2'h1: out = in_1;
            2'h2: out = in_2;
            2'h3: out = in_3;
            default:
                out = 'h0;
        endcase
    end
endmodule


module Mux_2x1_NBits #(
    parameter Bits = 2
)
(
    input [0:0] sel,
    input [(Bits - 1):0] in_0,
    input [(Bits - 1):0] in_1,
    output reg [(Bits - 1):0] out
);
    always @ (*) begin
        case (sel)
            1'h0: out = in_0;
            1'h1: out = in_1;
            default:
                out = 'h0;
        endcase
    end
endmodule


module Barrel_Shifter (
  input [15:0] DATA_IN,
  input [3:0] SHIFT_AMT,
  input \IsLeft? ,
  input ARIGHT_LOGIC,
  input \IsRotate? ,
  output [15:0] DATA_OUT
);
  wire [15:0] s0;
  wire [15:0] s1;
  wire s2;
  wire [15:0] s3;
  wire [31:0] s4;
  wire [31:0] s5;
  wire [31:0] s6;
  wire s7;
  wire s8;
  wire [31:0] s9;
  wire [31:0] s10;
  wire s11;
  wire [31:0] s12;
  wire [31:0] s13;
  wire s14;
  wire [31:0] s15;
  wire [31:0] s16;
  wire s17;
  wire [31:0] s18;
  wire [31:0] s19;
  wire [15:0] s20;
  wire [15:0] s21;
  assign s2 = DATA_IN[15];
  assign s8 = SHIFT_AMT[0];
  assign s11 = SHIFT_AMT[1];
  assign s14 = SHIFT_AMT[2];
  assign s17 = SHIFT_AMT[3];
  assign s0[0] = s2;
  assign s0[1] = DATA_IN[14];
  assign s0[2] = DATA_IN[13];
  assign s0[3] = DATA_IN[12];
  assign s0[4] = DATA_IN[11];
  assign s0[5] = DATA_IN[10];
  assign s0[6] = DATA_IN[9];
  assign s0[7] = DATA_IN[8];
  assign s0[8] = DATA_IN[7];
  assign s0[9] = DATA_IN[6];
  assign s0[10] = DATA_IN[5];
  assign s0[11] = DATA_IN[4];
  assign s0[12] = DATA_IN[3];
  assign s0[13] = DATA_IN[2];
  assign s0[14] = DATA_IN[1];
  assign s0[15] = DATA_IN[0];
  assign s7 = (s2 & ARIGHT_LOGIC);
  Mux_2x1_NBits #(
    .Bits(16)
  )
  Mux_2x1_NBits_i0 (
    .sel( \IsLeft?  ),
    .in_0( DATA_IN ),
    .in_1( s0 ),
    .out( s1 )
  );
  Mux_2x1_NBits #(
    .Bits(16)
  )
  Mux_2x1_NBits_i1 (
    .sel( s7 ),
    .in_0( 16'b0 ),
    .in_1( 16'b1111111111111111 ),
    .out( s3 )
  );
  assign s4[15:0] = s1;
  assign s4[31:16] = s3;
  assign s5[15:0] = s1;
  assign s5[31:16] = s1;
  Mux_2x1_NBits #(
    .Bits(32)
  )
  Mux_2x1_NBits_i2 (
    .sel( \IsRotate?  ),
    .in_0( s4 ),
    .in_1( s5 ),
    .out( s6 )
  );
  assign s9[30:0] = s6[31:1];
  assign s9[31] = 1'b0;
  Mux_2x1_NBits #(
    .Bits(32)
  )
  Mux_2x1_NBits_i3 (
    .sel( s8 ),
    .in_0( s6 ),
    .in_1( s9 ),
    .out( s10 )
  );
  assign s12[29:0] = s10[31:2];
  assign s12[31:30] = 2'b0;
  Mux_2x1_NBits #(
    .Bits(32)
  )
  Mux_2x1_NBits_i4 (
    .sel( s11 ),
    .in_0( s10 ),
    .in_1( s12 ),
    .out( s13 )
  );
  assign s15[27:0] = s13[31:4];
  assign s15[31:28] = 4'b0;
  Mux_2x1_NBits #(
    .Bits(32)
  )
  Mux_2x1_NBits_i5 (
    .sel( s14 ),
    .in_0( s13 ),
    .in_1( s15 ),
    .out( s16 )
  );
  assign s18[23:0] = s16[31:8];
  assign s18[31:24] = 8'b0;
  Mux_2x1_NBits #(
    .Bits(32)
  )
  Mux_2x1_NBits_i6 (
    .sel( s17 ),
    .in_0( s16 ),
    .in_1( s18 ),
    .out( s19 )
  );
  assign s20 = s19[15:0];
  assign s21[0] = s20[15];
  assign s21[1] = s20[14];
  assign s21[2] = s20[13];
  assign s21[3] = s20[12];
  assign s21[4] = s20[11];
  assign s21[5] = s20[10];
  assign s21[6] = s20[9];
  assign s21[7] = s20[8];
  assign s21[8] = s20[7];
  assign s21[9] = s20[6];
  assign s21[10] = s20[5];
  assign s21[11] = s20[4];
  assign s21[12] = s20[3];
  assign s21[13] = s20[2];
  assign s21[14] = s20[1];
  assign s21[15] = s20[0];
  Mux_2x1_NBits #(
    .Bits(16)
  )
  Mux_2x1_NBits_i7 (
    .sel( \IsLeft?  ),
    .in_0( s20 ),
    .in_1( s21 ),
    .out( DATA_OUT )
  );
endmodule

module DemuxBus2
#(
    parameter Bits = 2,
    parameter Default = 0 
)
(
    output [(Bits-1):0] out_0,
    output [(Bits-1):0] out_1,
    output [(Bits-1):0] out_2,
    output [(Bits-1):0] out_3,
    input [1:0] sel,
    input [(Bits-1):0] in
);
    assign out_0 = (sel == 2'h0)? in : Default;
    assign out_1 = (sel == 2'h1)? in : Default;
    assign out_2 = (sel == 2'h2)? in : Default;
    assign out_3 = (sel == 2'h3)? in : Default;
endmodule


module Mux_16x1_NBits #(
    parameter Bits = 2
)
(
    input [3:0] sel,
    input [(Bits - 1):0] in_0,
    input [(Bits - 1):0] in_1,
    input [(Bits - 1):0] in_2,
    input [(Bits - 1):0] in_3,
    input [(Bits - 1):0] in_4,
    input [(Bits - 1):0] in_5,
    input [(Bits - 1):0] in_6,
    input [(Bits - 1):0] in_7,
    input [(Bits - 1):0] in_8,
    input [(Bits - 1):0] in_9,
    input [(Bits - 1):0] in_10,
    input [(Bits - 1):0] in_11,
    input [(Bits - 1):0] in_12,
    input [(Bits - 1):0] in_13,
    input [(Bits - 1):0] in_14,
    input [(Bits - 1):0] in_15,
    output reg [(Bits - 1):0] out
);
    always @ (*) begin
        case (sel)
            4'h0: out = in_0;
            4'h1: out = in_1;
            4'h2: out = in_2;
            4'h3: out = in_3;
            4'h4: out = in_4;
            4'h5: out = in_5;
            4'h6: out = in_6;
            4'h7: out = in_7;
            4'h8: out = in_8;
            4'h9: out = in_9;
            4'ha: out = in_10;
            4'hb: out = in_11;
            4'hc: out = in_12;
            4'hd: out = in_13;
            4'he: out = in_14;
            4'hf: out = in_15;
            default:
                out = 'h0;
        endcase
    end
endmodule


module DIG_Counter_Nbit
#(
    parameter Bits = 2
)
(
    output [(Bits-1):0] out,
    output ovf,
    input C,
    input en,
    input clr
);
    reg [(Bits-1):0] count;

    always @ (posedge C) begin
        if (clr)
          count <= 'h0;
        else if (en)
          count <= count + 1'b1;
    end

    assign out = count;
    assign ovf = en? &count : 1'b0;

    initial begin
        count = 'h0;
    end
endmodule


module ALU (
  input En,
  input [3:0] Opcode,
  input [15:0] A,
  input [15:0] B,
  input CLK,
  input Carry_In,
  input Borrow_In,
  input [3:0] TARGET_ADDR,
  output SCU_EN,
  output LSU_EN,
  output [15:0] OUT,
  output [3:0] TARGET,
  output WE // Enable Write

);
  wire [15:0] s0;
  wire [15:0] s1;
  wire [15:0] SUM;
  wire CARRY;
  wire [15:0] s2;
  wire s3;
  wire s4;
  wire s5;
  wire s6;
  wire s7;
  wire s8;
  wire s9;
  wire s10;
  wire s11;
  wire s12;
  wire s13;
  wire s14;
  wire s15;
  wire s16;
  wire s17;
  wire s18;
  wire s19;
  wire [15:0] s20;
  wire s21;
  wire s22;
  wire s23;
  wire s24;
  wire s25;
  wire s26;
  wire s27;
  wire s28;
  wire s29;
  wire s30;
  wire s31;
  wire s32;
  wire s33;
  wire s34;
  wire s35;
  wire s36;
  wire s37;
  wire s38;
  wire s39;
  wire s40;
  wire s41;
  wire s42;
  wire s43;
  wire s44;
  wire s45;
  wire s46;
  wire s47;
  wire s48;
  wire s49;
  wire s50;
  wire s51;
  wire SCU_EN_temp;
  wire LSU_EN_temp;
  wire s52;
  wire s53;
  wire s54;
  wire s55;
  wire s56;
  wire s57;
  wire s58;
  wire s59;
  wire s60;
  wire s61;
  wire s62;
  wire s63;
  wire s64;
  wire s65;
  wire [3:0] s66;
  wire s67;
  wire s68;
  wire s69;
  wire s70;
  wire s71;
  wire s72;
  wire s73;
  wire s74;
  wire s75;
  wire s76;
  wire s77;
  wire s78;
  wire s79;
  wire s80;
  wire s81;
  wire s82;
  wire [15:0] s83;
  wire s84;
  wire s85;
  wire s86;
  wire s87;
  wire s88;
  wire s89;
  wire s90;
  wire s91;
  wire s92;
  wire s93;
  wire s94;
  wire s95;
  wire s96;
  wire s97;
  wire s98;
  wire s99;
  wire [15:0] s100;
  wire [15:0] SUB;
  wire BORROW;
  wire s101;
  wire s102;
  wire s103;
  wire s104;
  wire s105;
  wire s106;
  wire s107;
  wire s108;
  wire s109;
  wire s110;
  wire s111;
  wire s112;
  wire s113;
  wire s114;
  wire s115;
  wire s116;
  wire [15:0] s117;
  wire s118;
  wire s119;
  wire s120;
  wire s121;
  wire s122;
  wire s123;
  wire s124;
  wire s125;
  wire s126;
  wire s127;
  wire s128;
  wire s129;
  wire s130;
  wire s131;
  wire s132;
  wire s133;
  wire [15:0] s134;
  wire [31:0] s135;
  wire [15:0] MUL_LOW;
  wire s136;
  wire s137;
  wire s138;
  wire s139;
  wire s140;
  wire s141;
  wire s142;
  wire s143;
  wire s144;
  wire s145;
  wire s146;
  wire s147;
  wire s148;
  wire s149;
  wire s150;
  wire s151;
  wire [15:0] s152;
  wire s153;
  wire s154;
  wire s155;
  wire s156;
  wire s157;
  wire s158;
  wire s159;
  wire s160;
  wire s161;
  wire s162;
  wire s163;
  wire s164;
  wire s165;
  wire s166;
  wire s167;
  wire s168;
  wire [15:0] s169;
  wire [31:0] s170;
  wire [15:0] MUL_HIGH;
  wire [15:0] s171;
  wire [15:0] s172;
  wire [15:0] \AND ;
  wire s173;
  wire s174;
  wire s175;
  wire s176;
  wire s177;
  wire s178;
  wire s179;
  wire s180;
  wire s181;
  wire s182;
  wire s183;
  wire s184;
  wire s185;
  wire s186;
  wire s187;
  wire s188;
  wire s189;
  wire s190;
  wire s191;
  wire s192;
  wire s193;
  wire s194;
  wire s195;
  wire s196;
  wire s197;
  wire s198;
  wire s199;
  wire s200;
  wire s201;
  wire s202;
  wire s203;
  wire s204;
  wire s205;
  wire s206;
  wire s207;
  wire s208;
  wire s209;
  wire s210;
  wire s211;
  wire s212;
  wire s213;
  wire s214;
  wire s215;
  wire s216;
  wire s217;
  wire s218;
  wire s219;
  wire s220;
  wire [15:0] s221;
  wire s222;
  wire s223;
  wire s224;
  wire s225;
  wire s226;
  wire s227;
  wire s228;
  wire s229;
  wire s230;
  wire s231;
  wire s232;
  wire s233;
  wire s234;
  wire s235;
  wire s236;
  wire s237;
  wire [15:0] s238;
  wire [15:0] \XOR ;
  wire s239;
  wire s240;
  wire s241;
  wire s242;
  wire s243;
  wire s244;
  wire s245;
  wire s246;
  wire s247;
  wire s248;
  wire s249;
  wire s250;
  wire s251;
  wire s252;
  wire s253;
  wire s254;
  wire [15:0] s255;
  wire s256;
  wire s257;
  wire s258;
  wire s259;
  wire s260;
  wire s261;
  wire s262;
  wire s263;
  wire s264;
  wire s265;
  wire s266;
  wire s267;
  wire s268;
  wire s269;
  wire s270;
  wire s271;
  wire [15:0] s272;
  wire [15:0] \OR ;
  wire s273;
  wire s274;
  wire s275;
  wire s276;
  wire s277;
  wire s278;
  wire s279;
  wire s280;
  wire s281;
  wire s282;
  wire s283;
  wire s284;
  wire s285;
  wire s286;
  wire s287;
  wire s288;
  wire [15:0] s289;
  wire [15:0] \NOT ;
  wire s290;
  wire s291;
  wire s292;
  wire s293;
  wire s294;
  wire s295;
  wire s296;
  wire s297;
  wire s298;
  wire s299;
  wire s300;
  wire s301;
  wire s302;
  wire s303;
  wire s304;
  wire s305;
  wire [15:0] s306;
  wire s307;
  wire s308;
  wire s309;
  wire s310;
  wire s311;
  wire s312;
  wire s313;
  wire s314;
  wire s315;
  wire s316;
  wire s317;
  wire s318;
  wire s319;
  wire s320;
  wire s321;
  wire s322;
  wire [15:0] s323;
  wire [3:0] s324;
  wire [3:0] s325;
  wire s326;
  wire s327;
  wire s328;
  wire s329;
  wire s330;
  wire s331;
  wire s332;
  wire s333;
  wire s334;
  wire s335;
  wire s336;
  wire s337;
  wire s338;
  wire s339;
  wire s340;
  wire s341;
  wire [15:0] s342;
  wire [3:0] s343;
  wire [15:0] s344;
  wire [15:0] s345;
  wire s346;
  wire s347;
  wire s348;
  wire s349;
  wire s350;
  wire s351;
  wire s352;
  wire s353;
  wire s354;
  wire s355;
  wire s356;
  wire s357;
  wire s358;
  wire s359;
  wire s360;
  wire s361;
  wire s362;
  wire s363;
  wire s364;
  wire s365;
  wire s366;
  wire s367;
  wire s368;
  wire s369;
  wire s370;
  wire s371;
  wire s372;
  wire s373;
  wire s374;
  wire s375;
  wire s376;
  wire s377;
  wire s378;
  wire [15:0] s379;
  wire [15:0] s380;
  wire s381;
  wire s382;
  wire s383;
  wire s384;
  wire s385;
  wire s386;
  wire s387;
  wire s388;
  wire s389;
  wire s390;
  wire s391;
  wire s392;
  wire s393;
  wire s394;
  wire s395;
  wire s396;
  wire s397;
  wire s398;
  wire s399;
  wire s400;
  wire s401;
  wire s402;
  wire s403;
  wire s404;
  wire s405;
  wire s406;
  wire s407;
  wire s408;
  wire s409;
  wire s410;
  wire s411;
  wire s412;
  wire s413;
  wire s414;
  wire s415;
  wire s416;
  wire s417;
  wire s418;
  wire s419;
  wire s420;
  wire s421;
  wire s422;
  wire s423;
  wire s424;
  wire s425;
  wire s426;
  wire s427;
  wire s428;
  wire s429;
  wire [15:0] s430;
  wire [3:0] s431;
  wire [3:0] s432;
  wire [3:0] s433;
  wire [3:0] s434;
  wire [3:0] s435;
  wire [15:0] s436;
  wire [3:0] s437;
  wire s438;
  wire s439;
  wire s440;
  wire [15:0] s441;
  wire [1:0] s442;
  wire [15:0] SAR;
  wire [15:0] SHR;
  wire [15:0] SHL;
  wire [15:0] ROR;
  wire [15:0] SLT;
  wire [15:0] SLTU;
  wire s443;
  wire s444;
  wire [1:0] s445;
  wire s446;
  \16_BitDecoderWithEnablePin  \16_BitDecoderWithEnablePin_i0 (
    .EN( En ),
    .Sel_4Bit( Opcode ),
    .Q0( s38 ),
    .Q1( s39 ),
    .Q2( s40 ),
    .Q3( s41 ),
    .Q4( s42 ),
    .Q5( s43 ),
    .Q6( s44 ),
    .Q7( s45 ),
    .Q8( s46 ),
    .Q9( s47 ),
    .Q10( s48 ),
    .Q11( s49 ),
    .Q12( s50 ),
    .Q13( s51 ),
    .Q14( SCU_EN_temp ),
    .Q15( LSU_EN_temp )
  );
  DIG_D_FF_Nbit #(
    .Bits(4),
    .Default(0)
  )
  DIG_D_FF_Nbit_i1 (
    .D( TARGET_ADDR ),
    .C( CLK ),
    .Q( TARGET )
  );
  assign s37 = (~ (LSU_EN_temp | SCU_EN_temp) & En);
  ALU_RegCtrl ALU_RegCtrl_i2 (
    .\IsEn?_Decoder ( s37 ),
    .CLK( CLK ),
    .\0x0 ( s38 ),
    .\0x1 ( s39 ),
    .\0x2 ( s40 ),
    .\0x3 ( s41 ),
    .\0x4 ( s42 ),
    .\0x5 ( s43 ),
    .\0x6 ( s44 ),
    .\0x7 ( s45 ),
    .\0x8 ( s46 ),
    .\0x9 ( s47 ),
    .\0xA ( s48 ),
    .\0xB ( s49 ),
    .\0xC ( s50 ),
    .\0xD ( s51 ),
    .\0xE ( SCU_EN_temp ),
    .\0xF ( LSU_EN_temp ),
    .OPCODE_IN( Opcode ),
    .Q_0( s3 ),
    .Q_1( s52 ),
    .Q_2( s53 ),
    .Q_3( s54 ),
    .Q_4( s55 ),
    .Q_5( s56 ),
    .Q_6( s57 ),
    .Q_7( s58 ),
    .Q_8( s59 ),
    .Q_9( s60 ),
    .Q_A( s61 ),
    .Q_B( s62 ),
    .Q_C( s63 ),
    .Q_D( s64 ),
    .RST( s65 ),
    .OPCODE_OUT( s66 )
  );
  ALU_RegRST ALU_RegRST_i3 (
    .D( A ),
    .RST( s65 ),
    .Q( s2 )
  );
  ALU_RegRST ALU_RegRST_i4 (
    .D( B ),
    .RST( s65 ),
    .Q( s20 )
  );
  PriorityEncoder2 PriorityEncoder2_i5 (
    .in0( s59 ),
    .in1( s60 ),
    .in2( s61 ),
    .in3( s64 ),
    .num( s442 )
  );
  assign s443 = ~ s65;
  \16_BitRegister  \16_BitRegister_i6 (
    .D( s2 ),
    .EN( s3 ),
    .CLK( CLK ),
    .Q0( s4 ),
    .Q1( s5 ),
    .Q2( s6 ),
    .Q3( s7 ),
    .Q4( s8 ),
    .Q5( s9 ),
    .Q6( s10 ),
    .Q7( s11 ),
    .Q8( s12 ),
    .Q9( s13 ),
    .Q10( s14 ),
    .Q11( s15 ),
    .Q12( s16 ),
    .Q13( s17 ),
    .Q14( s18 ),
    .Q15( s19 )
  );
  \16_BitRegister  \16_BitRegister_i7 (
    .D( s20 ),
    .EN( s3 ),
    .CLK( CLK ),
    .Q0( s21 ),
    .Q1( s22 ),
    .Q2( s23 ),
    .Q3( s24 ),
    .Q4( s25 ),
    .Q5( s26 ),
    .Q6( s27 ),
    .Q7( s28 ),
    .Q8( s29 ),
    .Q9( s30 ),
    .Q10( s31 ),
    .Q11( s32 ),
    .Q12( s33 ),
    .Q13( s34 ),
    .Q14( s35 ),
    .Q15( s36 )
  );
  \16_BitRegister  \16_BitRegister_i8 (
    .D( s2 ),
    .EN( s52 ),
    .CLK( CLK ),
    .Q0( s67 ),
    .Q1( s68 ),
    .Q2( s69 ),
    .Q3( s70 ),
    .Q4( s71 ),
    .Q5( s72 ),
    .Q6( s73 ),
    .Q7( s74 ),
    .Q8( s75 ),
    .Q9( s76 ),
    .Q10( s77 ),
    .Q11( s78 ),
    .Q12( s79 ),
    .Q13( s80 ),
    .Q14( s81 ),
    .Q15( s82 )
  );
  \16_BitRegister  \16_BitRegister_i9 (
    .D( s20 ),
    .EN( s52 ),
    .CLK( CLK ),
    .Q0( s84 ),
    .Q1( s85 ),
    .Q2( s86 ),
    .Q3( s87 ),
    .Q4( s88 ),
    .Q5( s89 ),
    .Q6( s90 ),
    .Q7( s91 ),
    .Q8( s92 ),
    .Q9( s93 ),
    .Q10( s94 ),
    .Q11( s95 ),
    .Q12( s96 ),
    .Q13( s97 ),
    .Q14( s98 ),
    .Q15( s99 )
  );
  \16_BitRegister  \16_BitRegister_i10 (
    .D( s2 ),
    .EN( s53 ),
    .CLK( CLK ),
    .Q0( s101 ),
    .Q1( s102 ),
    .Q2( s103 ),
    .Q3( s104 ),
    .Q4( s105 ),
    .Q5( s106 ),
    .Q6( s107 ),
    .Q7( s108 ),
    .Q8( s109 ),
    .Q9( s110 ),
    .Q10( s111 ),
    .Q11( s112 ),
    .Q12( s113 ),
    .Q13( s114 ),
    .Q14( s115 ),
    .Q15( s116 )
  );
  \16_BitRegister  \16_BitRegister_i11 (
    .D( s20 ),
    .EN( s53 ),
    .CLK( CLK ),
    .Q0( s118 ),
    .Q1( s119 ),
    .Q2( s120 ),
    .Q3( s121 ),
    .Q4( s122 ),
    .Q5( s123 ),
    .Q6( s124 ),
    .Q7( s125 ),
    .Q8( s126 ),
    .Q9( s127 ),
    .Q10( s128 ),
    .Q11( s129 ),
    .Q12( s130 ),
    .Q13( s131 ),
    .Q14( s132 ),
    .Q15( s133 )
  );
  \16_BitRegister  \16_BitRegister_i12 (
    .D( s2 ),
    .EN( s54 ),
    .CLK( CLK ),
    .Q0( s136 ),
    .Q1( s137 ),
    .Q2( s138 ),
    .Q3( s139 ),
    .Q4( s140 ),
    .Q5( s141 ),
    .Q6( s142 ),
    .Q7( s143 ),
    .Q8( s144 ),
    .Q9( s145 ),
    .Q10( s146 ),
    .Q11( s147 ),
    .Q12( s148 ),
    .Q13( s149 ),
    .Q14( s150 ),
    .Q15( s151 )
  );
  \16_BitRegister  \16_BitRegister_i13 (
    .D( s20 ),
    .EN( s54 ),
    .CLK( CLK ),
    .Q0( s153 ),
    .Q1( s154 ),
    .Q2( s155 ),
    .Q3( s156 ),
    .Q4( s157 ),
    .Q5( s158 ),
    .Q6( s159 ),
    .Q7( s160 ),
    .Q8( s161 ),
    .Q9( s162 ),
    .Q10( s163 ),
    .Q11( s164 ),
    .Q12( s165 ),
    .Q13( s166 ),
    .Q14( s167 ),
    .Q15( s168 )
  );
  \16_BitRegister  \16_BitRegister_i14 (
    .D( s2 ),
    .EN( s55 ),
    .CLK( CLK ),
    .Q0( s173 ),
    .Q1( s174 ),
    .Q2( s175 ),
    .Q3( s176 ),
    .Q4( s177 ),
    .Q5( s178 ),
    .Q6( s179 ),
    .Q7( s180 ),
    .Q8( s181 ),
    .Q9( s182 ),
    .Q10( s183 ),
    .Q11( s184 ),
    .Q12( s185 ),
    .Q13( s186 ),
    .Q14( s187 ),
    .Q15( s188 )
  );
  \16_BitRegister  \16_BitRegister_i15 (
    .D( s20 ),
    .EN( s55 ),
    .CLK( CLK ),
    .Q0( s189 ),
    .Q1( s190 ),
    .Q2( s191 ),
    .Q3( s192 ),
    .Q4( s193 ),
    .Q5( s194 ),
    .Q6( s195 ),
    .Q7( s196 ),
    .Q8( s197 ),
    .Q9( s198 ),
    .Q10( s199 ),
    .Q11( s200 ),
    .Q12( s201 ),
    .Q13( s202 ),
    .Q14( s203 ),
    .Q15( s204 )
  );
  \16_BitRegister  \16_BitRegister_i16 (
    .D( s2 ),
    .EN( s56 ),
    .CLK( CLK ),
    .Q0( s205 ),
    .Q1( s206 ),
    .Q2( s207 ),
    .Q3( s208 ),
    .Q4( s209 ),
    .Q5( s210 ),
    .Q6( s211 ),
    .Q7( s212 ),
    .Q8( s213 ),
    .Q9( s214 ),
    .Q10( s215 ),
    .Q11( s216 ),
    .Q12( s217 ),
    .Q13( s218 ),
    .Q14( s219 ),
    .Q15( s220 )
  );
  \16_BitRegister  \16_BitRegister_i17 (
    .D( s20 ),
    .EN( s56 ),
    .CLK( CLK ),
    .Q0( s222 ),
    .Q1( s223 ),
    .Q2( s224 ),
    .Q3( s225 ),
    .Q4( s226 ),
    .Q5( s227 ),
    .Q6( s228 ),
    .Q7( s229 ),
    .Q8( s230 ),
    .Q9( s231 ),
    .Q10( s232 ),
    .Q11( s233 ),
    .Q12( s234 ),
    .Q13( s235 ),
    .Q14( s236 ),
    .Q15( s237 )
  );
  \16_BitRegister  \16_BitRegister_i18 (
    .D( s2 ),
    .EN( s57 ),
    .CLK( CLK ),
    .Q0( s239 ),
    .Q1( s240 ),
    .Q2( s241 ),
    .Q3( s242 ),
    .Q4( s243 ),
    .Q5( s244 ),
    .Q6( s245 ),
    .Q7( s246 ),
    .Q8( s247 ),
    .Q9( s248 ),
    .Q10( s249 ),
    .Q11( s250 ),
    .Q12( s251 ),
    .Q13( s252 ),
    .Q14( s253 ),
    .Q15( s254 )
  );
  \16_BitRegister  \16_BitRegister_i19 (
    .D( s20 ),
    .EN( s57 ),
    .CLK( CLK ),
    .Q0( s256 ),
    .Q1( s257 ),
    .Q2( s258 ),
    .Q3( s259 ),
    .Q4( s260 ),
    .Q5( s261 ),
    .Q6( s262 ),
    .Q7( s263 ),
    .Q8( s264 ),
    .Q9( s265 ),
    .Q10( s266 ),
    .Q11( s267 ),
    .Q12( s268 ),
    .Q13( s269 ),
    .Q14( s270 ),
    .Q15( s271 )
  );
  \16_BitRegister  \16_BitRegister_i20 (
    .D( s2 ),
    .EN( s58 ),
    .CLK( CLK ),
    .Q0( s273 ),
    .Q1( s274 ),
    .Q2( s275 ),
    .Q3( s276 ),
    .Q4( s277 ),
    .Q5( s278 ),
    .Q6( s279 ),
    .Q7( s280 ),
    .Q8( s281 ),
    .Q9( s282 ),
    .Q10( s283 ),
    .Q11( s284 ),
    .Q12( s285 ),
    .Q13( s286 ),
    .Q14( s287 ),
    .Q15( s288 )
  );
  \16_BitRegister  \16_BitRegister_i21 (
    .D( s2 ),
    .EN( s59 ),
    .CLK( CLK ),
    .Q0( s290 ),
    .Q1( s291 ),
    .Q2( s292 ),
    .Q3( s293 ),
    .Q4( s294 ),
    .Q5( s295 ),
    .Q6( s296 ),
    .Q7( s297 ),
    .Q8( s298 ),
    .Q9( s299 ),
    .Q10( s300 ),
    .Q11( s301 ),
    .Q12( s302 ),
    .Q13( s303 ),
    .Q14( s304 ),
    .Q15( s305 )
  );
  \16_BitRegister  \16_BitRegister_i22 (
    .D( s2 ),
    .EN( s60 ),
    .CLK( CLK ),
    .Q0( s307 ),
    .Q1( s308 ),
    .Q2( s309 ),
    .Q3( s310 ),
    .Q4( s311 ),
    .Q5( s312 ),
    .Q6( s313 ),
    .Q7( s314 ),
    .Q8( s315 ),
    .Q9( s316 ),
    .Q10( s317 ),
    .Q11( s318 ),
    .Q12( s319 ),
    .Q13( s320 ),
    .Q14( s321 ),
    .Q15( s322 )
  );
  \16_BitRegister  \16_BitRegister_i23 (
    .D( s2 ),
    .EN( s61 ),
    .CLK( CLK ),
    .Q0( s326 ),
    .Q1( s327 ),
    .Q2( s328 ),
    .Q3( s329 ),
    .Q4( s330 ),
    .Q5( s331 ),
    .Q6( s332 ),
    .Q7( s333 ),
    .Q8( s334 ),
    .Q9( s335 ),
    .Q10( s336 ),
    .Q11( s337 ),
    .Q12( s338 ),
    .Q13( s339 ),
    .Q14( s340 ),
    .Q15( s341 )
  );
  \16_BitRegister  \16_BitRegister_i24 (
    .D( s2 ),
    .EN( s62 ),
    .CLK( CLK ),
    .Q0( s347 ),
    .Q1( s348 ),
    .Q2( s349 ),
    .Q3( s350 ),
    .Q4( s351 ),
    .Q5( s352 ),
    .Q6( s353 ),
    .Q7( s354 ),
    .Q8( s355 ),
    .Q9( s356 ),
    .Q10( s357 ),
    .Q11( s358 ),
    .Q12( s359 ),
    .Q13( s360 ),
    .Q14( s361 ),
    .Q15( s362 )
  );
  \16_BitRegister  \16_BitRegister_i25 (
    .D( s20 ),
    .EN( s62 ),
    .CLK( CLK ),
    .Q0( s363 ),
    .Q1( s364 ),
    .Q2( s365 ),
    .Q3( s366 ),
    .Q4( s367 ),
    .Q5( s368 ),
    .Q6( s369 ),
    .Q7( s370 ),
    .Q8( s371 ),
    .Q9( s372 ),
    .Q10( s373 ),
    .Q11( s374 ),
    .Q12( s375 ),
    .Q13( s376 ),
    .Q14( s377 ),
    .Q15( s378 )
  );
  \16_BitRegister  \16_BitRegister_i26 (
    .D( s2 ),
    .EN( s63 ),
    .CLK( CLK ),
    .Q0( s382 ),
    .Q1( s383 ),
    .Q2( s384 ),
    .Q3( s385 ),
    .Q4( s386 ),
    .Q5( s387 ),
    .Q6( s388 ),
    .Q7( s389 ),
    .Q8( s390 ),
    .Q9( s391 ),
    .Q10( s392 ),
    .Q11( s393 ),
    .Q12( s394 ),
    .Q13( s395 ),
    .Q14( s396 ),
    .Q15( s397 )
  );
  \16_BitRegister  \16_BitRegister_i27 (
    .D( s20 ),
    .EN( s63 ),
    .CLK( CLK ),
    .Q0( s398 ),
    .Q1( s399 ),
    .Q2( s400 ),
    .Q3( s401 ),
    .Q4( s402 ),
    .Q5( s403 ),
    .Q6( s404 ),
    .Q7( s405 ),
    .Q8( s406 ),
    .Q9( s407 ),
    .Q10( s408 ),
    .Q11( s409 ),
    .Q12( s410 ),
    .Q13( s411 ),
    .Q14( s412 ),
    .Q15( s413 )
  );
  \16_BitRegister  \16_BitRegister_i28 (
    .D( s2 ),
    .EN( s64 ),
    .CLK( CLK ),
    .Q0( s414 ),
    .Q1( s415 ),
    .Q2( s416 ),
    .Q3( s417 ),
    .Q4( s418 ),
    .Q5( s419 ),
    .Q6( s420 ),
    .Q7( s421 ),
    .Q8( s422 ),
    .Q9( s423 ),
    .Q10( s424 ),
    .Q11( s425 ),
    .Q12( s426 ),
    .Q13( s427 ),
    .Q14( s428 ),
    .Q15( s429 )
  );
  Mux_4x1 Mux_4x1_i29 (
    .sel( s442 ),
    .in_0( 1'b0 ),
    .in_1( 1'b0 ),
    .in_2( 1'b1 ),
    .in_3( 1'b0 ),
    .out( s438 )
  );
  Mux_4x1 Mux_4x1_i30 (
    .sel( s442 ),
    .in_0( 1'b1 ),
    .in_1( 1'b0 ),
    .in_2( 1'b0 ),
    .in_3( 1'b0 ),
    .out( s439 )
  );
  Mux_4x1 Mux_4x1_i31 (
    .sel( s442 ),
    .in_0( 1'b0 ),
    .in_1( 1'b0 ),
    .in_2( 1'b0 ),
    .in_3( 1'b1 ),
    .out( s440 )
  );
  assign s324 = s20[3:0];
  assign s325 = s20[3:0];
  assign s343 = s20[3:0];
  assign s431 = s20[3:0];
  assign s0[0] = s4;
  assign s0[1] = s5;
  assign s0[2] = s6;
  assign s0[3] = s7;
  assign s0[4] = s8;
  assign s0[5] = s9;
  assign s0[6] = s10;
  assign s0[7] = s11;
  assign s0[8] = s12;
  assign s0[9] = s13;
  assign s0[10] = s14;
  assign s0[11] = s15;
  assign s0[12] = s16;
  assign s0[13] = s17;
  assign s0[14] = s18;
  assign s0[15] = s19;
  assign s1[0] = s21;
  assign s1[1] = s22;
  assign s1[2] = s23;
  assign s1[3] = s24;
  assign s1[4] = s25;
  assign s1[5] = s26;
  assign s1[6] = s27;
  assign s1[7] = s28;
  assign s1[8] = s29;
  assign s1[9] = s30;
  assign s1[10] = s31;
  assign s1[11] = s32;
  assign s1[12] = s33;
  assign s1[13] = s34;
  assign s1[14] = s35;
  assign s1[15] = s36;
  assign s83[0] = s67;
  assign s83[1] = s68;
  assign s83[2] = s69;
  assign s83[3] = s70;
  assign s83[4] = s71;
  assign s83[5] = s72;
  assign s83[6] = s73;
  assign s83[7] = s74;
  assign s83[8] = s75;
  assign s83[9] = s76;
  assign s83[10] = s77;
  assign s83[11] = s78;
  assign s83[12] = s79;
  assign s83[13] = s80;
  assign s83[14] = s81;
  assign s83[15] = s82;
  assign s100[0] = s84;
  assign s100[1] = s85;
  assign s100[2] = s86;
  assign s100[3] = s87;
  assign s100[4] = s88;
  assign s100[5] = s89;
  assign s100[6] = s90;
  assign s100[7] = s91;
  assign s100[8] = s92;
  assign s100[9] = s93;
  assign s100[10] = s94;
  assign s100[11] = s95;
  assign s100[12] = s96;
  assign s100[13] = s97;
  assign s100[14] = s98;
  assign s100[15] = s99;
  assign s117[0] = s101;
  assign s117[1] = s102;
  assign s117[2] = s103;
  assign s117[3] = s104;
  assign s117[4] = s105;
  assign s117[5] = s106;
  assign s117[6] = s107;
  assign s117[7] = s108;
  assign s117[8] = s109;
  assign s117[9] = s110;
  assign s117[10] = s111;
  assign s117[11] = s112;
  assign s117[12] = s113;
  assign s117[13] = s114;
  assign s117[14] = s115;
  assign s117[15] = s116;
  assign s134[0] = s118;
  assign s134[1] = s119;
  assign s134[2] = s120;
  assign s134[3] = s121;
  assign s134[4] = s122;
  assign s134[5] = s123;
  assign s134[6] = s124;
  assign s134[7] = s125;
  assign s134[8] = s126;
  assign s134[9] = s127;
  assign s134[10] = s128;
  assign s134[11] = s129;
  assign s134[12] = s130;
  assign s134[13] = s131;
  assign s134[14] = s132;
  assign s134[15] = s133;
  assign s152[0] = s136;
  assign s152[1] = s137;
  assign s152[2] = s138;
  assign s152[3] = s139;
  assign s152[4] = s140;
  assign s152[5] = s141;
  assign s152[6] = s142;
  assign s152[7] = s143;
  assign s152[8] = s144;
  assign s152[9] = s145;
  assign s152[10] = s146;
  assign s152[11] = s147;
  assign s152[12] = s148;
  assign s152[13] = s149;
  assign s152[14] = s150;
  assign s152[15] = s151;
  assign s169[0] = s153;
  assign s169[1] = s154;
  assign s169[2] = s155;
  assign s169[3] = s156;
  assign s169[4] = s157;
  assign s169[5] = s158;
  assign s169[6] = s159;
  assign s169[7] = s160;
  assign s169[8] = s161;
  assign s169[9] = s162;
  assign s169[10] = s163;
  assign s169[11] = s164;
  assign s169[12] = s165;
  assign s169[13] = s166;
  assign s169[14] = s167;
  assign s169[15] = s168;
  assign s171[0] = s173;
  assign s171[1] = s174;
  assign s171[2] = s175;
  assign s171[3] = s176;
  assign s171[4] = s177;
  assign s171[5] = s178;
  assign s171[6] = s179;
  assign s171[7] = s180;
  assign s171[8] = s181;
  assign s171[9] = s182;
  assign s171[10] = s183;
  assign s171[11] = s184;
  assign s171[12] = s185;
  assign s171[13] = s186;
  assign s171[14] = s187;
  assign s171[15] = s188;
  assign s172[0] = s189;
  assign s172[1] = s190;
  assign s172[2] = s191;
  assign s172[3] = s192;
  assign s172[4] = s193;
  assign s172[5] = s194;
  assign s172[6] = s195;
  assign s172[7] = s196;
  assign s172[8] = s197;
  assign s172[9] = s198;
  assign s172[10] = s199;
  assign s172[11] = s200;
  assign s172[12] = s201;
  assign s172[13] = s202;
  assign s172[14] = s203;
  assign s172[15] = s204;
  assign s221[0] = s205;
  assign s221[1] = s206;
  assign s221[2] = s207;
  assign s221[3] = s208;
  assign s221[4] = s209;
  assign s221[5] = s210;
  assign s221[6] = s211;
  assign s221[7] = s212;
  assign s221[8] = s213;
  assign s221[9] = s214;
  assign s221[10] = s215;
  assign s221[11] = s216;
  assign s221[12] = s217;
  assign s221[13] = s218;
  assign s221[14] = s219;
  assign s221[15] = s220;
  assign s238[0] = s222;
  assign s238[1] = s223;
  assign s238[2] = s224;
  assign s238[3] = s225;
  assign s238[4] = s226;
  assign s238[5] = s227;
  assign s238[6] = s228;
  assign s238[7] = s229;
  assign s238[8] = s230;
  assign s238[9] = s231;
  assign s238[10] = s232;
  assign s238[11] = s233;
  assign s238[12] = s234;
  assign s238[13] = s235;
  assign s238[14] = s236;
  assign s238[15] = s237;
  assign s255[0] = s239;
  assign s255[1] = s240;
  assign s255[2] = s241;
  assign s255[3] = s242;
  assign s255[4] = s243;
  assign s255[5] = s244;
  assign s255[6] = s245;
  assign s255[7] = s246;
  assign s255[8] = s247;
  assign s255[9] = s248;
  assign s255[10] = s249;
  assign s255[11] = s250;
  assign s255[12] = s251;
  assign s255[13] = s252;
  assign s255[14] = s253;
  assign s255[15] = s254;
  assign s272[0] = s256;
  assign s272[1] = s257;
  assign s272[2] = s258;
  assign s272[3] = s259;
  assign s272[4] = s260;
  assign s272[5] = s261;
  assign s272[6] = s262;
  assign s272[7] = s263;
  assign s272[8] = s264;
  assign s272[9] = s265;
  assign s272[10] = s266;
  assign s272[11] = s267;
  assign s272[12] = s268;
  assign s272[13] = s269;
  assign s272[14] = s270;
  assign s272[15] = s271;
  assign s289[0] = s273;
  assign s289[1] = s274;
  assign s289[2] = s275;
  assign s289[3] = s276;
  assign s289[4] = s277;
  assign s289[5] = s278;
  assign s289[6] = s279;
  assign s289[7] = s280;
  assign s289[8] = s281;
  assign s289[9] = s282;
  assign s289[10] = s283;
  assign s289[11] = s284;
  assign s289[12] = s285;
  assign s289[13] = s286;
  assign s289[14] = s287;
  assign s289[15] = s288;
  assign s306[0] = s290;
  assign s306[1] = s291;
  assign s306[2] = s292;
  assign s306[3] = s293;
  assign s306[4] = s294;
  assign s306[5] = s295;
  assign s306[6] = s296;
  assign s306[7] = s297;
  assign s306[8] = s298;
  assign s306[9] = s299;
  assign s306[10] = s300;
  assign s306[11] = s301;
  assign s306[12] = s302;
  assign s306[13] = s303;
  assign s306[14] = s304;
  assign s306[15] = s305;
  assign s323[0] = s307;
  assign s323[1] = s308;
  assign s323[2] = s309;
  assign s323[3] = s310;
  assign s323[4] = s311;
  assign s323[5] = s312;
  assign s323[6] = s313;
  assign s323[7] = s314;
  assign s323[8] = s315;
  assign s323[9] = s316;
  assign s323[10] = s317;
  assign s323[11] = s318;
  assign s323[12] = s319;
  assign s323[13] = s320;
  assign s323[14] = s321;
  assign s323[15] = s322;
  assign s342[0] = s326;
  assign s342[1] = s327;
  assign s342[2] = s328;
  assign s342[3] = s329;
  assign s342[4] = s330;
  assign s342[5] = s331;
  assign s342[6] = s332;
  assign s342[7] = s333;
  assign s342[8] = s334;
  assign s342[9] = s335;
  assign s342[10] = s336;
  assign s342[11] = s337;
  assign s342[12] = s338;
  assign s342[13] = s339;
  assign s342[14] = s340;
  assign s342[15] = s341;
  assign s344[0] = s347;
  assign s344[1] = s348;
  assign s344[2] = s349;
  assign s344[3] = s350;
  assign s344[4] = s351;
  assign s344[5] = s352;
  assign s344[6] = s353;
  assign s344[7] = s354;
  assign s344[8] = s355;
  assign s344[9] = s356;
  assign s344[10] = s357;
  assign s344[11] = s358;
  assign s344[12] = s359;
  assign s344[13] = s360;
  assign s344[14] = s361;
  assign s344[15] = s362;
  assign s345[0] = s363;
  assign s345[1] = s364;
  assign s345[2] = s365;
  assign s345[3] = s366;
  assign s345[4] = s367;
  assign s345[5] = s368;
  assign s345[6] = s369;
  assign s345[7] = s370;
  assign s345[8] = s371;
  assign s345[9] = s372;
  assign s345[10] = s373;
  assign s345[11] = s374;
  assign s345[12] = s375;
  assign s345[13] = s376;
  assign s345[14] = s377;
  assign s345[15] = s378;
  assign s379[0] = s382;
  assign s379[1] = s383;
  assign s379[2] = s384;
  assign s379[3] = s385;
  assign s379[4] = s386;
  assign s379[5] = s387;
  assign s379[6] = s388;
  assign s379[7] = s389;
  assign s379[8] = s390;
  assign s379[9] = s391;
  assign s379[10] = s392;
  assign s379[11] = s393;
  assign s379[12] = s394;
  assign s379[13] = s395;
  assign s379[14] = s396;
  assign s379[15] = s397;
  assign s380[0] = s398;
  assign s380[1] = s399;
  assign s380[2] = s400;
  assign s380[3] = s401;
  assign s380[4] = s402;
  assign s380[5] = s403;
  assign s380[6] = s404;
  assign s380[7] = s405;
  assign s380[8] = s406;
  assign s380[9] = s407;
  assign s380[10] = s408;
  assign s380[11] = s409;
  assign s380[12] = s410;
  assign s380[13] = s411;
  assign s380[14] = s412;
  assign s380[15] = s413;
  assign s430[0] = s414;
  assign s430[1] = s415;
  assign s430[2] = s416;
  assign s430[3] = s417;
  assign s430[4] = s418;
  assign s430[5] = s419;
  assign s430[6] = s420;
  assign s430[7] = s421;
  assign s430[8] = s422;
  assign s430[9] = s423;
  assign s430[10] = s424;
  assign s430[11] = s425;
  assign s430[12] = s426;
  assign s430[13] = s427;
  assign s430[14] = s428;
  assign s430[15] = s429;
  // 4-bit reg
  DIG_Register_BUS #(
    .Bits(4)
  )
  DIG_Register_BUS_i32 (
    .D( s431 ),
    .C( CLK ),
    .en( s64 ),
    .Q( s432 )
  );
  // 4-bit reg
  DIG_Register_BUS #(
    .Bits(4)
  )
  DIG_Register_BUS_i33 (
    .D( s343 ),
    .C( CLK ),
    .en( s61 ),
    .Q( s433 )
  );
  // 4-bit reg
  DIG_Register_BUS #(
    .Bits(4)
  )
  DIG_Register_BUS_i34 (
    .D( s324 ),
    .C( CLK ),
    .en( s60 ),
    .Q( s434 )
  );
  // 4-bit reg
  DIG_Register_BUS #(
    .Bits(4)
  )
  DIG_Register_BUS_i35 (
    .D( s325 ),
    .C( CLK ),
    .en( s59 ),
    .Q( s435 )
  );
  DIG_Add #(
    .Bits(16)
  )
  DIG_Add_i36 (
    .a( s0 ),
    .b( s1 ),
    .c_i( Carry_In ),
    .s( SUM ),
    .c_o( CARRY )
  );
  DIG_Sub #(
    .Bits(16)
  )
  DIG_Sub_i37 (
    .a( s83 ),
    .b( s100 ),
    .c_i( Borrow_In ),
    .s( SUB ),
    .c_o( BORROW )
  );
  DIG_Mul_signed #(
    .Bits(16)
  )
  DIG_Mul_signed_i38 (
    .a( s117 ),
    .b( s134 ),
    .mul( s135 )
  );
  DIG_Mul_signed #(
    .Bits(16)
  )
  DIG_Mul_signed_i39 (
    .a( s152 ),
    .b( s169 ),
    .mul( s170 )
  );
  \16_BitAndOP  \16_BitAndOP_i40 (
    .A( s171 ),
    .B( s172 ),
    .Q( \AND  )
  );
  \16_BitXorOP  \16_BitXorOP_i41 (
    .A( s221 ),
    .B( s238 ),
    .Q( \XOR  )
  );
  \16_BitOrOP  \16_BitOrOP_i42 (
    .A( s255 ),
    .B( s272 ),
    .Q( \OR  )
  );
  \16_BitNotOP  \16_BitNotOP_i43 (
    .D( s289 ),
    .Q( \NOT  )
  );
  CompSigned #(
    .Bits(16)
  )
  CompSigned_i44 (
    .a( s344 ),
    .b( s345 ),
    .\< ( s346 )
  );
  CompUnsigned #(
    .Bits(16)
  )
  CompUnsigned_i45 (
    .a( s379 ),
    .b( s380 ),
    .\< ( s381 )
  );
  Mux_4x1_NBits #(
    .Bits(16)
  )
  Mux_4x1_NBits_i46 (
    .sel( s442 ),
    .in_0( s306 ),
    .in_1( s323 ),
    .in_2( s342 ),
    .in_3( s430 ),
    .out( s436 )
  );
  Mux_4x1_NBits #(
    .Bits(4)
  )
  Mux_4x1_NBits_i47 (
    .sel( s442 ),
    .in_0( s435 ),
    .in_1( s434 ),
    .in_2( s433 ),
    .in_3( s432 ),
    .out( s437 )
  );
  Barrel_Shifter Barrel_Shifter_i48 (
    .DATA_IN( s436 ),
    .SHIFT_AMT( s437 ),
    .\IsLeft? ( s438 ),
    .ARIGHT_LOGIC( s439 ),
    .\IsRotate? ( s440 ),
    .DATA_OUT( s441 )
  );
  assign SLT[0] = s346;
  assign SLT[15:1] = 15'b0;
  assign SLTU[0] = s381;
  assign SLTU[15:1] = 15'b0;
  assign MUL_LOW = s135[15:0];
  assign MUL_HIGH = s170[31:16];
  DemuxBus2 #(
    .Bits(16),
    .Default(0)
  )
  DemuxBus2_i49 (
    .sel( s442 ),
    .in( s441 ),
    .out_0( SAR ),
    .out_1( SHR ),
    .out_2( SHL ),
    .out_3( ROR )
  );
  Mux_16x1_NBits #(
    .Bits(16)
  )
  Mux_16x1_NBits_i50 (
    .sel( s66 ),
    .in_0( SUM ),
    .in_1( SUB ),
    .in_2( MUL_LOW ),
    .in_3( MUL_HIGH ),
    .in_4( \AND  ),
    .in_5( \XOR  ),
    .in_6( \OR  ),
    .in_7( \NOT  ),
    .in_8( SAR ),
    .in_9( SHR ),
    .in_10( SHL ),
    .in_11( SLT ),
    .in_12( SLTU ),
    .in_13( ROR ),
    .in_14( 16'b0 ),
    .in_15( 16'b0 ),
    .out( OUT )
  );
  DIG_Counter_Nbit #(
    .Bits(2)
  )
  DIG_Counter_Nbit_i51 (
    .en( s443 ),
    .C( CLK ),
    .clr( s444 ),
    .out( s445 ),
    .ovf( s446 )
  );
  assign s444 = (s65 | s446);
  assign WE = (s445[0] & s445[1]);
  assign SCU_EN = SCU_EN_temp;
  assign LSU_EN = LSU_EN_temp;
endmodule
