/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */

module Mux_2x1_NBits #(
    parameter Bits = 2
)
(
    input [0:0] sel,
    input [(Bits - 1):0] in_0,
    input [(Bits - 1):0] in_1,
    output reg [(Bits - 1):0] out
);
    always @ (*) begin
        case (sel)
            1'h0: out = in_0;
            1'h1: out = in_1;
            default:
                out = 'h0;
        endcase
    end
endmodule


module Barrel_Shifter (
  input [15:0] DATA_IN,
  input LeftnotRight,
  input ARIGHT_LOGIC,
  input RotatenotShift,
  input [3:0] SHIFT_AMT,
  output [15:0] DATA_OUT
);
  wire [15:0] s0;
  wire [15:0] s1;
  wire s2;
  wire [15:0] s3;
  wire [31:0] s4;
  wire [31:0] s5;
  wire [31:0] s6;
  wire s7;
  wire s8;
  wire [31:0] s9;
  wire [31:0] s10;
  wire s11;
  wire [31:0] s12;
  wire [31:0] s13;
  wire s14;
  wire [31:0] s15;
  wire [31:0] s16;
  wire s17;
  wire [31:0] s18;
  wire [31:0] s19;
  wire [15:0] s20;
  wire [15:0] s21;
  assign s2 = DATA_IN[15];
  assign s8 = SHIFT_AMT[0];
  assign s11 = SHIFT_AMT[1];
  assign s14 = SHIFT_AMT[2];
  assign s17 = SHIFT_AMT[3];
  assign s0[0] = s2;
  assign s0[1] = DATA_IN[14];
  assign s0[2] = DATA_IN[13];
  assign s0[3] = DATA_IN[12];
  assign s0[4] = DATA_IN[11];
  assign s0[5] = DATA_IN[10];
  assign s0[6] = DATA_IN[9];
  assign s0[7] = DATA_IN[8];
  assign s0[8] = DATA_IN[7];
  assign s0[9] = DATA_IN[6];
  assign s0[10] = DATA_IN[5];
  assign s0[11] = DATA_IN[4];
  assign s0[12] = DATA_IN[3];
  assign s0[13] = DATA_IN[2];
  assign s0[14] = DATA_IN[1];
  assign s0[15] = DATA_IN[0];
  assign s7 = (s2 & ARIGHT_LOGIC);
  Mux_2x1_NBits #(
    .Bits(16)
  )
  Mux_2x1_NBits_i0 (
    .sel( LeftnotRight ),
    .in_0( DATA_IN ),
    .in_1( s0 ),
    .out( s1 )
  );
  Mux_2x1_NBits #(
    .Bits(16)
  )
  Mux_2x1_NBits_i1 (
    .sel( s7 ),
    .in_0( 16'b0 ),
    .in_1( 16'b1111111111111111 ),
    .out( s3 )
  );
  assign s4[15:0] = s1;
  assign s4[31:16] = s3;
  assign s5[15:0] = s1;
  assign s5[31:16] = s1;
  Mux_2x1_NBits #(
    .Bits(32)
  )
  Mux_2x1_NBits_i2 (
    .sel( RotatenotShift ),
    .in_0( s4 ),
    .in_1( s5 ),
    .out( s6 )
  );
  assign s9[30:0] = s6[31:1];
  assign s9[31] = 1'b0;
  Mux_2x1_NBits #(
    .Bits(32)
  )
  Mux_2x1_NBits_i3 (
    .sel( s8 ),
    .in_0( s6 ),
    .in_1( s9 ),
    .out( s10 )
  );
  assign s12[29:0] = s10[31:2];
  assign s12[31:30] = 2'b0;
  Mux_2x1_NBits #(
    .Bits(32)
  )
  Mux_2x1_NBits_i4 (
    .sel( s11 ),
    .in_0( s10 ),
    .in_1( s12 ),
    .out( s13 )
  );
  assign s15[27:0] = s13[31:4];
  assign s15[31:28] = 4'b0;
  Mux_2x1_NBits #(
    .Bits(32)
  )
  Mux_2x1_NBits_i5 (
    .sel( s14 ),
    .in_0( s13 ),
    .in_1( s15 ),
    .out( s16 )
  );
  assign s18[23:0] = s16[31:8];
  assign s18[31:24] = 8'b0;
  Mux_2x1_NBits #(
    .Bits(32)
  )
  Mux_2x1_NBits_i6 (
    .sel( s17 ),
    .in_0( s16 ),
    .in_1( s18 ),
    .out( s19 )
  );
  assign s20 = s19[15:0];
  assign s21[0] = s20[15];
  assign s21[1] = s20[14];
  assign s21[2] = s20[13];
  assign s21[3] = s20[12];
  assign s21[4] = s20[11];
  assign s21[5] = s20[10];
  assign s21[6] = s20[9];
  assign s21[7] = s20[8];
  assign s21[8] = s20[7];
  assign s21[9] = s20[6];
  assign s21[10] = s20[5];
  assign s21[11] = s20[4];
  assign s21[12] = s20[3];
  assign s21[13] = s20[2];
  assign s21[14] = s20[1];
  assign s21[15] = s20[0];
  Mux_2x1_NBits #(
    .Bits(16)
  )
  Mux_2x1_NBits_i7 (
    .sel( LeftnotRight ),
    .in_0( s20 ),
    .in_1( s21 ),
    .out( DATA_OUT )
  );
endmodule
