/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */

module DIG_Register
(
    input C,
    input en,
    input D,
    output Q
);

    reg  state = 'h0;

    assign Q = state;

    always @ (posedge C) begin
        if (en)
            state <= D;
   end
endmodule

module Driver
(
    input in,
    input sel,
    output out
);
    assign out = (sel == 1'b1)? in : 1'bz;
endmodule

module gpio_cell (
  input REG_WR,
  input OE,
  input PIN_IN,
  input CLK,
  input WE,
  output REG_RD,
  output PIN_OUT
);
  wire s0;
  DIG_Register DIG_Register_i0 (
    .D( REG_WR ),
    .C( CLK ),
    .en( WE ),
    .Q( s0 )
  );
  Driver Driver_i1 (
    .in( s0 ),
    .sel( OE ),
    .out( PIN_OUT )
  );
  assign REG_RD = PIN_IN;
endmodule
