/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */

module DIG_Register_BUS #(
    parameter Bits = 1
)
(
    input C,
    input en,
    input [(Bits - 1):0]D,
    output [(Bits - 1):0]Q
);

    reg [(Bits - 1):0] state = 'h0;

    assign Q = state;

    always @ (posedge C) begin
        if (en)
            state <= D;
   end
endmodule

module Decoder4 (
    output out_0,
    output out_1,
    output out_2,
    output out_3,
    output out_4,
    output out_5,
    output out_6,
    output out_7,
    output out_8,
    output out_9,
    output out_10,
    output out_11,
    output out_12,
    output out_13,
    output out_14,
    output out_15,
    input [3:0] sel
);
    assign out_0 = (sel == 4'h0)? 1'b1 : 1'b0;
    assign out_1 = (sel == 4'h1)? 1'b1 : 1'b0;
    assign out_2 = (sel == 4'h2)? 1'b1 : 1'b0;
    assign out_3 = (sel == 4'h3)? 1'b1 : 1'b0;
    assign out_4 = (sel == 4'h4)? 1'b1 : 1'b0;
    assign out_5 = (sel == 4'h5)? 1'b1 : 1'b0;
    assign out_6 = (sel == 4'h6)? 1'b1 : 1'b0;
    assign out_7 = (sel == 4'h7)? 1'b1 : 1'b0;
    assign out_8 = (sel == 4'h8)? 1'b1 : 1'b0;
    assign out_9 = (sel == 4'h9)? 1'b1 : 1'b0;
    assign out_10 = (sel == 4'ha)? 1'b1 : 1'b0;
    assign out_11 = (sel == 4'hb)? 1'b1 : 1'b0;
    assign out_12 = (sel == 4'hc)? 1'b1 : 1'b0;
    assign out_13 = (sel == 4'hd)? 1'b1 : 1'b0;
    assign out_14 = (sel == 4'he)? 1'b1 : 1'b0;
    assign out_15 = (sel == 4'hf)? 1'b1 : 1'b0;
endmodule


module \16_BitDecoderWithEnablePin  (
  input EN,
  input [3:0] Sel_4Bit,
  output Q0,
  output Q1,
  output Q2,
  output Q3,
  output Q4,
  output Q5,
  output Q6,
  output Q7,
  output Q8,
  output Q9,
  output Q10,
  output Q11,
  output Q12,
  output Q13,
  output Q14,
  output Q15
);
  wire s0;
  wire s1;
  wire s2;
  wire s3;
  wire s4;
  wire s5;
  wire s6;
  wire s7;
  wire s8;
  wire s9;
  wire s10;
  wire s11;
  wire s12;
  wire s13;
  wire s14;
  wire s15;
  Decoder4 Decoder4_i0 (
    .sel( Sel_4Bit ),
    .out_0( s0 ),
    .out_1( s1 ),
    .out_2( s2 ),
    .out_3( s3 ),
    .out_4( s4 ),
    .out_5( s5 ),
    .out_6( s6 ),
    .out_7( s7 ),
    .out_8( s8 ),
    .out_9( s9 ),
    .out_10( s10 ),
    .out_11( s11 ),
    .out_12( s12 ),
    .out_13( s13 ),
    .out_14( s14 ),
    .out_15( s15 )
  );
  assign Q0 = (EN & s0);
  assign Q1 = (EN & s1);
  assign Q2 = (EN & s2);
  assign Q3 = (EN & s3);
  assign Q4 = (EN & s4);
  assign Q5 = (EN & s5);
  assign Q6 = (EN & s6);
  assign Q7 = (EN & s7);
  assign Q8 = (EN & s8);
  assign Q9 = (EN & s9);
  assign Q10 = (EN & s10);
  assign Q11 = (EN & s11);
  assign Q12 = (EN & s12);
  assign Q13 = (EN & s13);
  assign Q14 = (EN & s14);
  assign Q15 = (EN & s15);
endmodule
module DIG_D_FF_1bit
#(
    parameter Default = 0
)
(
   input D,
   input C,
   output Q,
   output \~Q
);
    reg state;

    assign Q = state;
    assign \~Q = ~state;

    always @ (posedge C) begin
        state <= D;
    end

    initial begin
        state = Default;
    end
endmodule


module ALU_RegCtrl (
  input \IsEn?_Decoder ,
  input CLK,
  input \0x0 ,
  input \0x1 ,
  input \0x2 ,
  input \0x3 ,
  input \0x4 ,
  input \0x5 ,
  input \0x6 ,
  input \0x7 ,
  input \0x8 ,
  input \0x9 ,
  input \0xA ,
  input \0xB ,
  input \0xC ,
  input \0xD ,
  input \0xE ,
  input \0xF ,
  output Q_0,
  output Q_1,
  output Q_2,
  output Q_3,
  output Q_4,
  output Q_5,
  output Q_6,
  output Q_7,
  output Q_8,
  output Q_9,
  output Q_A,
  output Q_B,
  output Q_C,
  output Q_D,
  output Q_E,
  output Q_F,
  output RST
);
  wire RST_temp;
  wire s0;
  wire s1;
  wire s2;
  wire s3;
  wire s4;
  wire s5;
  wire s6;
  wire s7;
  wire s8;
  wire s9;
  wire s10;
  wire s11;
  wire s12;
  wire s13;
  wire s14;
  wire s15;
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i0 (
    .D( \0x0  ),
    .C( CLK ),
    .Q( s0 )
  );
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i1 (
    .D( \0x1  ),
    .C( CLK ),
    .Q( s1 )
  );
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i2 (
    .D( \0x2  ),
    .C( CLK ),
    .Q( s2 )
  );
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i3 (
    .D( \0x3  ),
    .C( CLK ),
    .Q( s3 )
  );
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i4 (
    .D( \0x4  ),
    .C( CLK ),
    .Q( s4 )
  );
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i5 (
    .D( \0x5  ),
    .C( CLK ),
    .Q( s5 )
  );
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i6 (
    .D( \0x6  ),
    .C( CLK ),
    .Q( s6 )
  );
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i7 (
    .D( \0x7  ),
    .C( CLK ),
    .Q( s7 )
  );
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i8 (
    .D( \0x8  ),
    .C( CLK ),
    .Q( s8 )
  );
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i9 (
    .D( \0x9  ),
    .C( CLK ),
    .Q( s9 )
  );
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i10 (
    .D( \0xA  ),
    .C( CLK ),
    .Q( s10 )
  );
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i11 (
    .D( \0xB  ),
    .C( CLK ),
    .Q( s11 )
  );
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i12 (
    .D( \0xC  ),
    .C( CLK ),
    .Q( s12 )
  );
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i13 (
    .D( \0xD  ),
    .C( CLK ),
    .Q( s13 )
  );
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i14 (
    .D( \0xE  ),
    .C( CLK ),
    .Q( s14 )
  );
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i15 (
    .D( \0xF  ),
    .C( CLK ),
    .Q( s15 )
  );
  assign RST_temp = ~ \IsEn?_Decoder ;
  assign Q_0 = (RST_temp | s0);
  assign Q_1 = (RST_temp | s1);
  assign Q_2 = (RST_temp | s2);
  assign Q_3 = (RST_temp | s3);
  assign Q_4 = (RST_temp | s4);
  assign Q_5 = (RST_temp | s5);
  assign Q_6 = (RST_temp | s6);
  assign Q_7 = (RST_temp | s7);
  assign Q_8 = (RST_temp | s8);
  assign Q_9 = (RST_temp | s9);
  assign Q_A = (RST_temp | s10);
  assign Q_B = (RST_temp | s11);
  assign Q_C = (RST_temp | s12);
  assign Q_D = (RST_temp | s13);
  assign Q_E = (RST_temp | s14);
  assign Q_F = (RST_temp | s15);
  assign RST = RST_temp;
endmodule

module DemuxBus4
#(
    parameter Bits = 2,
    parameter Default = 0 
)
(
    output [(Bits-1):0] out_0,
    output [(Bits-1):0] out_1,
    output [(Bits-1):0] out_2,
    output [(Bits-1):0] out_3,
    output [(Bits-1):0] out_4,
    output [(Bits-1):0] out_5,
    output [(Bits-1):0] out_6,
    output [(Bits-1):0] out_7,
    output [(Bits-1):0] out_8,
    output [(Bits-1):0] out_9,
    output [(Bits-1):0] out_10,
    output [(Bits-1):0] out_11,
    output [(Bits-1):0] out_12,
    output [(Bits-1):0] out_13,
    output [(Bits-1):0] out_14,
    output [(Bits-1):0] out_15,
    input [3:0] sel,
    input [(Bits-1):0] in
);
    assign out_0 = (sel == 4'h0)? in : Default;
    assign out_1 = (sel == 4'h1)? in : Default;
    assign out_2 = (sel == 4'h2)? in : Default;
    assign out_3 = (sel == 4'h3)? in : Default;
    assign out_4 = (sel == 4'h4)? in : Default;
    assign out_5 = (sel == 4'h5)? in : Default;
    assign out_6 = (sel == 4'h6)? in : Default;
    assign out_7 = (sel == 4'h7)? in : Default;
    assign out_8 = (sel == 4'h8)? in : Default;
    assign out_9 = (sel == 4'h9)? in : Default;
    assign out_10 = (sel == 4'ha)? in : Default;
    assign out_11 = (sel == 4'hb)? in : Default;
    assign out_12 = (sel == 4'hc)? in : Default;
    assign out_13 = (sel == 4'hd)? in : Default;
    assign out_14 = (sel == 4'he)? in : Default;
    assign out_15 = (sel == 4'hf)? in : Default;
endmodule


module ALU_RegRST (
  input [15:0] D,
  input RST,
  output [15:0] Q
);
  wire s0;
  assign s0 = ~ RST;
  assign Q[0] = (s0 & D[0]);
  assign Q[1] = (s0 & D[1]);
  assign Q[2] = (s0 & D[2]);
  assign Q[3] = (s0 & D[3]);
  assign Q[4] = (s0 & D[4]);
  assign Q[5] = (s0 & D[5]);
  assign Q[6] = (s0 & D[6]);
  assign Q[7] = (s0 & D[7]);
  assign Q[8] = (s0 & D[8]);
  assign Q[9] = (s0 & D[9]);
  assign Q[10] = (s0 & D[10]);
  assign Q[11] = (s0 & D[11]);
  assign Q[12] = (s0 & D[12]);
  assign Q[13] = (s0 & D[13]);
  assign Q[14] = (s0 & D[14]);
  assign Q[15] = (s0 & D[15]);
endmodule
module DIG_Add
#(
    parameter Bits = 1
)
(
    input [(Bits-1):0] a,
    input [(Bits-1):0] b,
    input c_i,
    output [(Bits - 1):0] s,
    output c_o
);
   wire [Bits:0] temp;

   assign temp = a + b + c_i;
   assign s = temp [(Bits-1):0];
   assign c_o = temp[Bits];
endmodule



module lsu (
  input LSU_EN,
  input [3:0] LSU_OP,
  input CLK,
  input [3:0] SOURCE,
  input [3:0] TARGET,
  input [15:0] DATA, // This pipeline get data from source register
  output [15:0] Register_DataOut,
  output [15:0] Memory_DataOut,
  output [15:0] \GPIO-REG_DataOut ,
  output [15:0] PC_DataOut,
  output [3:0] SOURCE_MEM,
  output [3:0] SOURCE_REG,
  output [3:0] SOURCE_IM,
  output [3:0] SOURCE_GPIO,
  output [3:0] TARGET_REG,
  output [3:0] TARGET_MEM,
  output [3:0] TARGET_GPIO,
  output [3:0] TARGET_PC,
  output Restore_PC,
  output SOURCE_FUNCREG,
  output PC_NPS // SEND NPS(NEXT PAGE SIGNAL) TO PC

);
  wire s0;
  wire s1;
  wire s2;
  wire s3;
  wire s4;
  wire s5;
  wire s6;
  wire s7;
  wire s8;
  wire s9;
  wire s10;
  wire s11;
  wire s12;
  wire s13;
  wire s14;
  wire s15;
  wire s16;
  wire s17;
  wire s18;
  wire s19;
  wire s20;
  wire s21;
  wire s22;
  wire s23;
  wire s24;
  wire s25;
  wire s26;
  wire s27;
  wire s28;
  wire s29;
  wire s30;
  wire s31;
  wire [3:0] s32;
  wire [3:0] s33;
  wire [15:0] s34;
  wire s35;
  wire [15:0] s36;
  wire [7:0] s37;
  wire s38;
  wire [7:0] s39;
  wire [15:0] s40;
  wire [15:0] s41;
  wire [15:0] s42;
  wire [15:0] s43;
  wire [15:0] s44;
  wire [15:0] s45;
  wire [15:0] s46;
  wire [15:0] s47;
  wire [15:0] s48;
  wire [15:0] s49;
  wire [15:0] s50;
  wire [15:0] s51;
  wire [15:0] s52;
  wire [15:0] s53;
  wire [15:0] s54;
  wire [15:0] s55;
  wire [15:0] s56;
  wire [15:0] s57;
  wire [15:0] s58;
  wire [15:0] s59;
  wire [3:0] s60;
  wire [3:0] s61;
  wire [3:0] s62;
  wire [3:0] s63;
  wire [3:0] s64;
  wire [3:0] s65;
  wire [3:0] s66;
  wire [3:0] s67;
  wire [3:0] s68;
  wire [3:0] s69;
  wire [3:0] s70;
  wire [3:0] s71;
  wire [3:0] s72;
  wire [3:0] s73;
  wire [3:0] s74;
  wire [3:0] s75;
  wire [3:0] s76;
  wire [3:0] s77;
  wire [3:0] s78;
  wire [3:0] s79;
  wire [3:0] s80;
  wire [3:0] s81;
  wire [3:0] s82;
  wire [3:0] s83;
  wire [3:0] s84;
  wire [3:0] s85;
  wire [3:0] s86;
  wire [3:0] s87;
  wire [3:0] s88;
  wire [15:0] s89;
  wire [15:0] s90;
  wire s91;
  wire s92;
  wire s93;
  wire s94;
  DIG_Register_BUS #(
    .Bits(4)
  )
  DIG_Register_BUS_i0 (
    .D( SOURCE ),
    .C( CLK ),
    .en( LSU_EN ),
    .Q( s32 )
  );
  DIG_Register_BUS #(
    .Bits(4)
  )
  DIG_Register_BUS_i1 (
    .D( TARGET ),
    .C( CLK ),
    .en( LSU_EN ),
    .Q( s33 )
  );
  \16_BitDecoderWithEnablePin  \16_BitDecoderWithEnablePin_i2 (
    .EN( LSU_EN ),
    .Sel_4Bit( LSU_OP ),
    .Q0( s0 ),
    .Q1( s1 ),
    .Q2( s2 ),
    .Q3( s3 ),
    .Q4( s4 ),
    .Q5( s5 ),
    .Q6( s6 ),
    .Q7( s7 ),
    .Q8( s8 ),
    .Q9( s9 ),
    .Q10( s10 ),
    .Q11( s11 ),
    .Q12( s12 ),
    .Q13( s13 ),
    .Q14( s14 ),
    .Q15( s15 )
  );
  ALU_RegCtrl ALU_RegCtrl_i3 (
    .\IsEn?_Decoder ( LSU_EN ),
    .CLK( CLK ),
    .\0x0 ( s0 ),
    .\0x1 ( s1 ),
    .\0x2 ( s2 ),
    .\0x3 ( s3 ),
    .\0x4 ( s4 ),
    .\0x5 ( s5 ),
    .\0x6 ( s6 ),
    .\0x7 ( s7 ),
    .\0x8 ( s8 ),
    .\0x9 ( s9 ),
    .\0xA ( s10 ),
    .\0xB ( s11 ),
    .\0xC ( s12 ),
    .\0xD ( s13 ),
    .\0xE ( s14 ),
    .\0xF ( s15 ),
    .Q_1( s16 ),
    .Q_2( s17 ),
    .Q_3( s18 ),
    .Q_4( s19 ),
    .Q_5( s20 ),
    .Q_6( s21 ),
    .Q_7( s22 ),
    .Q_8( s23 ),
    .Q_9( s24 ),
    .Q_A( s25 ),
    .Q_B( s26 ),
    .Q_C( s27 ),
    .Q_D( s28 ),
    .Q_E( s29 ),
    .Q_F( s30 ),
    .RST( s31 )
  );
  DemuxBus4 #(
    .Bits(4),
    .Default(0)
  )
  DemuxBus4_i4 (
    .sel( LSU_OP ),
    .in( s32 ),
    .out_1( s60 ),
    .out_2( s61 ),
    .out_3( s62 ),
    .out_4( s63 ),
    .out_5( s64 ),
    .out_6( SOURCE_GPIO ),
    .out_7( s65 ),
    .out_8( s66 ),
    .out_9( s67 ),
    .out_10( s68 ),
    .out_11( s69 ),
    .out_12( s70 ),
    .out_13( s71 ),
    .out_14( s72 ),
    .out_15( s73 )
  );
  DemuxBus4 #(
    .Bits(4),
    .Default(0)
  )
  DemuxBus4_i5 (
    .sel( LSU_OP ),
    .in( s33 ),
    .out_1( s74 ),
    .out_2( s75 ),
    .out_3( s76 ),
    .out_4( s77 ),
    .out_5( s78 ),
    .out_6( s79 ),
    .out_7( s80 ),
    .out_8( s81 ),
    .out_9( s82 ),
    .out_10( s83 ),
    .out_11( s84 ),
    .out_12( s85 ),
    .out_13( s86 ),
    .out_14( s87 ),
    .out_15( s88 )
  );
  assign s35 = (s29 | s27 | s25 | s24 | s28 | s26 | s17 | s19 | s20 | s21 | s22 | s23);
  assign s38 = (s18 | s16);
  assign SOURCE_MEM = (s60 | s61);
  assign SOURCE_REG = (s62 | s63 | s64 | s66 | s69 | s71);
  assign SOURCE_IM = (s67 | s65 | s68 | s70 | s72);
  assign TARGET_REG = (s74 | s75 | s79 | s81 | s82);
  assign TARGET_MEM = (s76 | s77 | s83);
  assign TARGET_GPIO = (s78 | s80);
  assign TARGET_PC = (s84 | s85 | s86 | s87 | s88);
  ALU_RegRST ALU_RegRST_i6 (
    .D( DATA ),
    .RST( s31 ),
    .Q( s34 )
  );
  assign s93 = ~ (s30 & s31);
  assign s94 = (~ s31 & s30);
  assign SOURCE_FUNCREG = s73[0];
  DIG_Register_BUS #(
    .Bits(16)
  )
  DIG_Register_BUS_i7 (
    .D( s34 ),
    .C( CLK ),
    .en( s35 ),
    .Q( s36 )
  );
  DIG_Add #(
    .Bits(16)
  )
  DIG_Add_i8 (
    .a( s34 ),
    .b( 16'b1 ),
    .c_i( 1'b0 ),
    .s( s89 ),
    .c_o( PC_NPS )
  );
  assign s91 = ~ (s35 & s31);
  assign s92 = ~ (s31 & s38);
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i9 (
    .D( s94 ),
    .C( CLK ),
    .Q( Restore_PC )
  );
  assign s37 = s34[7:0];
  DIG_Register_BUS #(
    .Bits(8)
  )
  DIG_Register_BUS_i10 (
    .D( s37 ),
    .C( CLK ),
    .en( s38 ),
    .Q( s39 )
  );
  DIG_Register_BUS #(
    .Bits(16)
  )
  DIG_Register_BUS_i11 (
    .D( s89 ),
    .C( CLK ),
    .en( s30 ),
    .Q( s90 )
  );
  ALU_RegRST ALU_RegRST_i12 (
    .D( s36 ),
    .RST( s91 ),
    .Q( s57 )
  );
  assign s40[7:0] = s39;
  assign s40[15:8] = 8'b0;
  ALU_RegRST ALU_RegRST_i13 (
    .D( s90 ),
    .RST( s93 ),
    .Q( s59 )
  );
  ALU_RegRST ALU_RegRST_i14 (
    .D( s40 ),
    .RST( s92 ),
    .Q( s58 )
  );
  assign s56 = (s57 | s58 | s59);
  DemuxBus4 #(
    .Bits(16),
    .Default(0)
  )
  DemuxBus4_i15 (
    .sel( LSU_OP ),
    .in( s56 ),
    .out_1( s41 ),
    .out_2( s42 ),
    .out_3( s43 ),
    .out_4( s44 ),
    .out_5( s45 ),
    .out_6( s46 ),
    .out_7( s47 ),
    .out_8( s48 ),
    .out_9( s49 ),
    .out_10( s50 ),
    .out_11( s51 ),
    .out_12( s52 ),
    .out_13( s53 ),
    .out_14( s54 ),
    .out_15( s55 )
  );
  assign Register_DataOut = (s41 | s42 | s46 | s48 | s49);
  assign Memory_DataOut = (s43 | s44 | s50);
  assign \GPIO-REG_DataOut  = (s45 | s47);
  assign PC_DataOut = (s51 | s52 | s53 | s54 | s55);
endmodule
