/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */
module DIG_JK_FF
#(
    parameter Default = 1'b0
)
(
   input J,
   input C,
   input K,
   output Q,
   output \~Q
);
    reg state;

    assign Q = state;
    assign \~Q = ~state;

    always @ (posedge C) begin
        if (~J & K)
            state <= 1'b0;
         else if (J & ~K)
            state <= 1'b1;
         else if (J & K)
            state <= ~state;
    end

    initial begin
        state = Default;
    end
endmodule


module ALU_RegRST (
  input [15:0] D,
  input RST,
  output [15:0] Q
);
  wire s0;
  assign s0 = ~ RST;
  assign Q[0] = (s0 & D[0]);
  assign Q[1] = (s0 & D[1]);
  assign Q[2] = (s0 & D[2]);
  assign Q[3] = (s0 & D[3]);
  assign Q[4] = (s0 & D[4]);
  assign Q[5] = (s0 & D[5]);
  assign Q[6] = (s0 & D[6]);
  assign Q[7] = (s0 & D[7]);
  assign Q[8] = (s0 & D[8]);
  assign Q[9] = (s0 & D[9]);
  assign Q[10] = (s0 & D[10]);
  assign Q[11] = (s0 & D[11]);
  assign Q[12] = (s0 & D[12]);
  assign Q[13] = (s0 & D[13]);
  assign Q[14] = (s0 & D[14]);
  assign Q[15] = (s0 & D[15]);
endmodule

module DIG_CounterPreset #(
    parameter Bits = 2,
    parameter maxValue = 4
)
(
    input C,
    input en,
    input clr,
    input dir,
    input [(Bits-1):0] in,
    input ld,
    output [(Bits-1):0] out,
    output ovf
);

    reg [(Bits-1):0] count = 'h0;

    function [(Bits-1):0] maxVal (input [(Bits-1):0] maxv);
        if (maxv == 0)
            maxVal = (1 << Bits) - 1;
        else
            maxVal = maxv;
    endfunction

    assign out = count;
    assign ovf = ((count == maxVal(maxValue) & dir == 1'b0)
                  | (count == 'b0 & dir == 1'b1))? en : 1'b0;

    always @ (posedge C) begin
        if (clr == 1'b1)
            count <= 'h0;
        else if (ld == 1'b1)
            count <= in;
        else if (en == 1'b1) begin
            if (dir == 1'b0) begin
                if (count == maxVal(maxValue))
                    count <= 'h0;
                else
                    count <= count + 1'b1;
            end
            else begin
                if (count == 'h0)
                    count <= maxVal(maxValue);
                else
                    count <= count - 1;
            end
        end
    end
endmodule

module DIG_BlockRAMDualPort
#(
    parameter Bits = 8,
    parameter AddrBits = 4
)
(
  input [(AddrBits-1):0] A,
  input [(Bits-1):0] Din,
  input str,
  input C,
  output [(Bits-1):0] D
);
  reg [(Bits-1):0] memory[0:((1 << AddrBits) - 1)];
  reg [(Bits-1):0] wData;

  assign D = wData;

  always @ (posedge C) begin
    wData <= memory[A];
    if (str)
      memory[A] <= Din;
  end
endmodule

module DIG_D_FF_1bit
#(
    parameter Default = 0
)
(
   input D,
   input C,
   output Q,
   output \~Q
);
    reg state;

    assign Q = state;
    assign \~Q = ~state;

    always @ (posedge C) begin
        state <= D;
    end

    initial begin
        state = Default;
    end
endmodule


module PC (
  input [15:0] D_ISRAM, // Data input for instraction memory
  input WE_ISRAM, // Write enable input for instraction memory
  input [15:0] D_Page, // Data input for Page Counter
  input [7:0] ADDR_ISRAM, // Adress input for instraction memory
  input WE_Page, // Write Enable input for Page Counter
  input WE_PC, // Write enable input for Program Counter
  input [7:0] ADDR_PC, // Adress input for Program Counter
  input RST_PC, // Reset input for Program Counter
  input RST_Page,
  input CLK,
  input Disable_PC, // Disable input for Program Counter
  output [15:0] Page_Num, // Page Number out
  output [15:0] IS_Out // Instraction Output

);
  wire s0;
  wire [7:0] s1;
  wire s2;
  wire s3;
  wire s4;
  wire [7:0] s5;
  wire s6;
  wire s7;
  wire [15:0] s8;
  wire [15:0] s9;
  wire s10;
  wire s11;
  assign s7 = ~ Disable_PC;
  assign s8[7:0] = ADDR_ISRAM;
  assign s8[15:8] = 8'b0;
  DIG_JK_FF #(
    .Default(0)
  )
  DIG_JK_FF_i0 (
    .J( 1'b1 ),
    .C( CLK ),
    .K( 1'b1 ),
    .Q( s10 )
  );
  ALU_RegRST ALU_RegRST_i1 (
    .D( s8 ),
    .RST( s7 ),
    .Q( s9 )
  );
  DIG_JK_FF #(
    .Default(0)
  )
  DIG_JK_FF_i2 (
    .J( s10 ),
    .C( CLK ),
    .K( s10 ),
    .Q( s11 )
  );
  assign s0 = (s7 & (s10 & s11));
  // Program Counter(PC)
  DIG_CounterPreset #(
    .Bits(8),
    .maxValue(0)
  )
  DIG_CounterPreset_i3 (
    .en( s0 ),
    .C( CLK ),
    .dir( 1'b0 ),
    .in( ADDR_PC ),
    .ld( WE_PC ),
    .clr( RST_PC ),
    .out( s1 ),
    .ovf( s2 )
  );
  assign s5 = (s9[7:0] | s1);
  // Instraction Memory
  DIG_BlockRAMDualPort #(
    .Bits(16),
    .AddrBits(8)
  )
  DIG_BlockRAMDualPort_i4 (
    .A( s5 ),
    .Din( D_ISRAM ),
    .str( WE_ISRAM ),
    .C( CLK ),
    .D( IS_Out )
  );
  // Page Counter(Page)
  DIG_CounterPreset #(
    .Bits(16),
    .maxValue(0)
  )
  DIG_CounterPreset_i5 (
    .en( s2 ),
    .C( CLK ),
    .dir( 1'b0 ),
    .in( D_Page ),
    .ld( WE_Page ),
    .clr( s3 ),
    .out( Page_Num ),
    .ovf( s4 )
  );
  assign s3 = (RST_Page | s6);
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i6 (
    .D( s4 ),
    .C( CLK ),
    .Q( s6 )
  );
endmodule
