/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */

module Decoder4 (
    output out_0,
    output out_1,
    output out_2,
    output out_3,
    output out_4,
    output out_5,
    output out_6,
    output out_7,
    output out_8,
    output out_9,
    output out_10,
    output out_11,
    output out_12,
    output out_13,
    output out_14,
    output out_15,
    input [3:0] sel
);
    assign out_0 = (sel == 4'h0)? 1'b1 : 1'b0;
    assign out_1 = (sel == 4'h1)? 1'b1 : 1'b0;
    assign out_2 = (sel == 4'h2)? 1'b1 : 1'b0;
    assign out_3 = (sel == 4'h3)? 1'b1 : 1'b0;
    assign out_4 = (sel == 4'h4)? 1'b1 : 1'b0;
    assign out_5 = (sel == 4'h5)? 1'b1 : 1'b0;
    assign out_6 = (sel == 4'h6)? 1'b1 : 1'b0;
    assign out_7 = (sel == 4'h7)? 1'b1 : 1'b0;
    assign out_8 = (sel == 4'h8)? 1'b1 : 1'b0;
    assign out_9 = (sel == 4'h9)? 1'b1 : 1'b0;
    assign out_10 = (sel == 4'ha)? 1'b1 : 1'b0;
    assign out_11 = (sel == 4'hb)? 1'b1 : 1'b0;
    assign out_12 = (sel == 4'hc)? 1'b1 : 1'b0;
    assign out_13 = (sel == 4'hd)? 1'b1 : 1'b0;
    assign out_14 = (sel == 4'he)? 1'b1 : 1'b0;
    assign out_15 = (sel == 4'hf)? 1'b1 : 1'b0;
endmodule

module DIG_BlockRAMDualPort
#(
    parameter Bits = 8,
    parameter AddrBits = 4
)
(
  input [(AddrBits-1):0] A,
  input [(Bits-1):0] Din,
  input str,
  input C,
  output [(Bits-1):0] D
);
  reg [(Bits-1):0] memory[0:((1 << AddrBits) - 1)];
  reg [(Bits-1):0] wData;

  assign D = wData;

  always @ (posedge C) begin
    wData <= memory[A];
    if (str)
      memory[A] <= Din;
  end
endmodule


module DIG_Register_BUS #(
    parameter Bits = 1
)
(
    input C,
    input en,
    input [(Bits - 1):0]D,
    output [(Bits - 1):0]Q
);

    reg [(Bits - 1):0] state = 'h0;

    assign Q = state;

    always @ (posedge C) begin
        if (en)
            state <= D;
   end
endmodule

module DIG_Register
(
    input C,
    input en,
    input D,
    output Q
);

    reg  state = 'h0;

    assign Q = state;

    always @ (posedge C) begin
        if (en)
            state <= D;
   end
endmodule

module Mux_16x1_NBits #(
    parameter Bits = 2
)
(
    input [3:0] sel,
    input [(Bits - 1):0] in_0,
    input [(Bits - 1):0] in_1,
    input [(Bits - 1):0] in_2,
    input [(Bits - 1):0] in_3,
    input [(Bits - 1):0] in_4,
    input [(Bits - 1):0] in_5,
    input [(Bits - 1):0] in_6,
    input [(Bits - 1):0] in_7,
    input [(Bits - 1):0] in_8,
    input [(Bits - 1):0] in_9,
    input [(Bits - 1):0] in_10,
    input [(Bits - 1):0] in_11,
    input [(Bits - 1):0] in_12,
    input [(Bits - 1):0] in_13,
    input [(Bits - 1):0] in_14,
    input [(Bits - 1):0] in_15,
    output reg [(Bits - 1):0] out
);
    always @ (*) begin
        case (sel)
            4'h0: out = in_0;
            4'h1: out = in_1;
            4'h2: out = in_2;
            4'h3: out = in_3;
            4'h4: out = in_4;
            4'h5: out = in_5;
            4'h6: out = in_6;
            4'h7: out = in_7;
            4'h8: out = in_8;
            4'h9: out = in_9;
            4'ha: out = in_10;
            4'hb: out = in_11;
            4'hc: out = in_12;
            4'hd: out = in_13;
            4'he: out = in_14;
            4'hf: out = in_15;
            default:
                out = 'h0;
        endcase
    end
endmodule


module Mux_2x1
(
    input [0:0] sel,
    input in_0,
    input in_1,
    output reg out
);
    always @ (*) begin
        case (sel)
            1'h0: out = in_0;
            1'h1: out = in_1;
            default:
                out = 'h0;
        endcase
    end
endmodule


module Mux_16x1
(
    input [3:0] sel,
    input in_0,
    input in_1,
    input in_2,
    input in_3,
    input in_4,
    input in_5,
    input in_6,
    input in_7,
    input in_8,
    input in_9,
    input in_10,
    input in_11,
    input in_12,
    input in_13,
    input in_14,
    input in_15,
    output reg out
);
    always @ (*) begin
        case (sel)
            4'h0: out = in_0;
            4'h1: out = in_1;
            4'h2: out = in_2;
            4'h3: out = in_3;
            4'h4: out = in_4;
            4'h5: out = in_5;
            4'h6: out = in_6;
            4'h7: out = in_7;
            4'h8: out = in_8;
            4'h9: out = in_9;
            4'ha: out = in_10;
            4'hb: out = in_11;
            4'hc: out = in_12;
            4'hd: out = in_13;
            4'he: out = in_14;
            4'hf: out = in_15;
            default:
                out = 'h0;
        endcase
    end
endmodule


module RegisterFile (
  input CLK,
  input [15:0] D,
  input [3:0] GPREG_InSEL,
  input [3:0] GPREG_OutSEL,
  input [3:0] IO_InSel,
  input [3:0] IO_OutSel,
  input [15:0] BRAM_ADDR,
  input BRAM_WE,
  input [3:0] SetMod_IO,
  input GPIO_IN0x0,
  input GPIO_IN0x1,
  input GPIO_IN0x2,
  input GPIO_IN0x3,
  input GPIO_IN0x4,
  input GPIO_IN0x5,
  input GPIO_IN0x6,
  input GPIO_IN0x7,
  input GPIO_IN0x8,
  input GPIO_IN0x9,
  input GPIO_IN0xA,
  input GPIO_IN0xB,
  input GPIO_IN0xC,
  input GPIO_IN0xD,
  input GPIO_IN0xE,
  input GPIO_IN0xF,
  output [15:0] GPREG_UOT,
  output GPIO_OUT0x0,
  output GPIO_DataOUT,
  output [15:0] BRAM_OUT,
  output GPIO_OUT0x1,
  output GPIO_OUT0x2,
  output GPIO_OUT0x3,
  output GPIO_OUT0x4,
  output GPIO_OUT0x5,
  output GPIO_OUT0x6,
  output GPIO_OUT0x7,
  output GPIO_OUT0x8,
  output GPIO_OUT0x9,
  output GPIO_OUT0xA,
  output GPIO_OUT0xB,
  output GPIO_OUT0xC,
  output GPIO_OUT0xD,
  output GPIO_OUT0xE,
  output GPIO_OUT0xF
);
  wire s0;
  wire [15:0] s1;
  wire s2;
  wire [15:0] s3;
  wire s4;
  wire [15:0] s5;
  wire s6;
  wire [15:0] s7;
  wire s8;
  wire [15:0] s9;
  wire s10;
  wire [15:0] s11;
  wire s12;
  wire [15:0] s13;
  wire s14;
  wire [15:0] s15;
  wire s16;
  wire [15:0] s17;
  wire s18;
  wire [15:0] s19;
  wire s20;
  wire [15:0] s21;
  wire s22;
  wire [15:0] s23;
  wire s24;
  wire [15:0] s25;
  wire s26;
  wire [15:0] s27;
  wire s28;
  wire [15:0] s29;
  wire s30;
  wire [15:0] s31;
  wire s32;
  wire s33;
  wire s34;
  wire s35;
  wire s36;
  wire s37;
  wire s38;
  wire s39;
  wire s40;
  wire s41;
  wire s42;
  wire s43;
  wire s44;
  wire s45;
  wire s46;
  wire s47;
  wire s48;
  wire s49;
  wire s50;
  wire s51;
  wire s52;
  wire s53;
  wire s54;
  wire s55;
  wire s56;
  wire s57;
  wire s58;
  wire s59;
  wire s60;
  wire s61;
  wire s62;
  wire s63;
  wire s64;
  wire s65;
  wire s66;
  wire s67;
  wire s68;
  wire s69;
  wire s70;
  wire s71;
  wire s72;
  wire s73;
  wire s74;
  wire s75;
  wire s76;
  wire s77;
  wire s78;
  wire s79;
  wire s80;
  wire s81;
  wire s82;
  wire s83;
  wire s84;
  wire s85;
  wire s86;
  wire s87;
  wire s88;
  wire s89;
  wire s90;
  wire s91;
  wire s92;
  wire s93;
  wire s94;
  wire s95;
  wire s96;
  wire s97;
  wire s98;
  wire s99;
  wire s100;
  wire s101;
  wire s102;
  wire s103;
  wire s104;
  wire s105;
  wire s106;
  wire s107;
  wire s108;
  wire s109;
  wire s110;
  wire s111;
  wire s112;
  wire s113;
  wire s114;
  wire s115;
  wire s116;
  wire s117;
  wire s118;
  wire s119;
  wire s120;
  wire s121;
  wire s122;
  wire s123;
  wire s124;
  wire s125;
  wire s126;
  wire s127;
  wire s128;
  wire [3:0] s129;
  wire [3:0] s130;
  wire [3:0] s131;
  wire [3:0] s132;
  wire [15:0] s133;
  wire s134;
  wire s135;
  wire s136;
  wire s137;
  wire s138;
  wire s139;
  wire s140;
  wire s141;
  wire s142;
  wire s143;
  wire s144;
  wire s145;
  wire s146;
  wire s147;
  wire s148;
  wire s149;
  wire s150;
  wire s151;
  wire s152;
  wire s153;
  wire s154;
  wire s155;
  wire s156;
  wire s157;
  wire s158;
  wire s159;
  wire s160;
  wire s161;
  wire s162;
  wire s163;
  wire s164;
  wire s165;
  wire s166;
  wire s167;
  wire s168;
  wire s169;
  wire s170;
  wire s171;
  wire s172;
  wire s173;
  wire s174;
  wire s175;
  wire s176;
  wire s177;
  wire s178;
  wire s179;
  wire s180;
  wire s181;
  wire [15:0] s182;
  wire [7:0] s183;
  wire [7:0] s184;
  wire [15:0] s185;
  Decoder4 Decoder4_i0 (
    .sel( GPREG_InSEL ),
    .out_0( s0 ),
    .out_1( s2 ),
    .out_2( s4 ),
    .out_3( s6 ),
    .out_4( s8 ),
    .out_5( s10 ),
    .out_6( s12 ),
    .out_7( s14 ),
    .out_8( s16 ),
    .out_9( s18 ),
    .out_10( s20 ),
    .out_11( s22 ),
    .out_12( s24 ),
    .out_13( s26 ),
    .out_14( s28 ),
    .out_15( s30 )
  );
  Decoder4 Decoder4_i1 (
    .sel( IO_InSel ),
    .out_0( s80 ),
    .out_1( s81 ),
    .out_2( s82 ),
    .out_3( s83 ),
    .out_4( s84 ),
    .out_5( s85 ),
    .out_6( s86 ),
    .out_7( s87 ),
    .out_8( s88 ),
    .out_9( s89 ),
    .out_10( s90 ),
    .out_11( s91 ),
    .out_12( s92 ),
    .out_13( s93 ),
    .out_14( s94 ),
    .out_15( s95 )
  );
  DIG_BlockRAMDualPort #(
    .Bits(16),
    .AddrBits(16)
  )
  DIG_BlockRAMDualPort_i2 (
    .A( BRAM_ADDR ),
    .Din( D ),
    .str( BRAM_WE ),
    .C( CLK ),
    .D( BRAM_OUT )
  );
  Decoder4 Decoder4_i3 (
    .sel( SetMod_IO ),
    .out_0( s97 ),
    .out_1( s99 ),
    .out_2( s101 ),
    .out_3( s103 ),
    .out_4( s105 ),
    .out_5( s107 ),
    .out_6( s109 ),
    .out_7( s111 ),
    .out_8( s113 ),
    .out_9( s115 ),
    .out_10( s117 ),
    .out_11( s119 ),
    .out_12( s121 ),
    .out_13( s123 ),
    .out_14( s125 ),
    .out_15( s127 )
  );
  assign s135 = D[0];
  assign s138 = D[1];
  assign s141 = D[2];
  assign s144 = D[3];
  assign s147 = D[4];
  assign s150 = D[5];
  assign s153 = D[6];
  assign s156 = D[7];
  assign s159 = D[8];
  assign s162 = D[9];
  assign s165 = D[10];
  assign s168 = D[11];
  assign s171 = D[12];
  assign s174 = D[13];
  assign s177 = D[14];
  assign s180 = D[15];
  assign s96 = D[0];
  DIG_Register_BUS #(
    .Bits(16)
  )
  DIG_Register_BUS_i4 (
    .D( D ),
    .C( CLK ),
    .en( s0 ),
    .Q( s1 )
  );
  DIG_Register_BUS #(
    .Bits(16)
  )
  DIG_Register_BUS_i5 (
    .D( D ),
    .C( CLK ),
    .en( s2 ),
    .Q( s3 )
  );
  DIG_Register_BUS #(
    .Bits(16)
  )
  DIG_Register_BUS_i6 (
    .D( D ),
    .C( CLK ),
    .en( s4 ),
    .Q( s5 )
  );
  DIG_Register_BUS #(
    .Bits(16)
  )
  DIG_Register_BUS_i7 (
    .D( D ),
    .C( CLK ),
    .en( s6 ),
    .Q( s7 )
  );
  DIG_Register_BUS #(
    .Bits(16)
  )
  DIG_Register_BUS_i8 (
    .D( D ),
    .C( CLK ),
    .en( s8 ),
    .Q( s9 )
  );
  DIG_Register_BUS #(
    .Bits(16)
  )
  DIG_Register_BUS_i9 (
    .D( D ),
    .C( CLK ),
    .en( s10 ),
    .Q( s11 )
  );
  DIG_Register_BUS #(
    .Bits(16)
  )
  DIG_Register_BUS_i10 (
    .D( D ),
    .C( CLK ),
    .en( s12 ),
    .Q( s13 )
  );
  DIG_Register_BUS #(
    .Bits(16)
  )
  DIG_Register_BUS_i11 (
    .D( D ),
    .C( CLK ),
    .en( s14 ),
    .Q( s15 )
  );
  DIG_Register_BUS #(
    .Bits(16)
  )
  DIG_Register_BUS_i12 (
    .D( D ),
    .C( CLK ),
    .en( s16 ),
    .Q( s17 )
  );
  DIG_Register_BUS #(
    .Bits(16)
  )
  DIG_Register_BUS_i13 (
    .D( D ),
    .C( CLK ),
    .en( s18 ),
    .Q( s19 )
  );
  DIG_Register_BUS #(
    .Bits(16)
  )
  DIG_Register_BUS_i14 (
    .D( D ),
    .C( CLK ),
    .en( s20 ),
    .Q( s21 )
  );
  DIG_Register_BUS #(
    .Bits(16)
  )
  DIG_Register_BUS_i15 (
    .D( D ),
    .C( CLK ),
    .en( s22 ),
    .Q( s23 )
  );
  DIG_Register_BUS #(
    .Bits(16)
  )
  DIG_Register_BUS_i16 (
    .D( D ),
    .C( CLK ),
    .en( s24 ),
    .Q( s25 )
  );
  DIG_Register_BUS #(
    .Bits(16)
  )
  DIG_Register_BUS_i17 (
    .D( D ),
    .C( CLK ),
    .en( s26 ),
    .Q( s27 )
  );
  DIG_Register_BUS #(
    .Bits(16)
  )
  DIG_Register_BUS_i18 (
    .D( D ),
    .C( CLK ),
    .en( s28 ),
    .Q( s29 )
  );
  DIG_Register_BUS #(
    .Bits(16)
  )
  DIG_Register_BUS_i19 (
    .D( D ),
    .C( CLK ),
    .en( s30 ),
    .Q( s31 )
  );
  DIG_Register DIG_Register_i20 (
    .D( s96 ),
    .C( CLK ),
    .en( s97 ),
    .Q( s98 )
  );
  DIG_Register DIG_Register_i21 (
    .D( s96 ),
    .C( CLK ),
    .en( s99 ),
    .Q( s100 )
  );
  DIG_Register DIG_Register_i22 (
    .D( s96 ),
    .C( CLK ),
    .en( s101 ),
    .Q( s102 )
  );
  DIG_Register DIG_Register_i23 (
    .D( s96 ),
    .C( CLK ),
    .en( s103 ),
    .Q( s104 )
  );
  DIG_Register DIG_Register_i24 (
    .D( s96 ),
    .C( CLK ),
    .en( s105 ),
    .Q( s106 )
  );
  DIG_Register DIG_Register_i25 (
    .D( s96 ),
    .C( CLK ),
    .en( s107 ),
    .Q( s108 )
  );
  DIG_Register DIG_Register_i26 (
    .D( s96 ),
    .C( CLK ),
    .en( s109 ),
    .Q( s110 )
  );
  DIG_Register DIG_Register_i27 (
    .D( s96 ),
    .C( CLK ),
    .en( s111 ),
    .Q( s112 )
  );
  DIG_Register DIG_Register_i28 (
    .D( s96 ),
    .C( CLK ),
    .en( s113 ),
    .Q( s114 )
  );
  DIG_Register DIG_Register_i29 (
    .D( s96 ),
    .C( CLK ),
    .en( s115 ),
    .Q( s116 )
  );
  DIG_Register DIG_Register_i30 (
    .D( s96 ),
    .C( CLK ),
    .en( s117 ),
    .Q( s118 )
  );
  DIG_Register DIG_Register_i31 (
    .D( s96 ),
    .C( CLK ),
    .en( s119 ),
    .Q( s120 )
  );
  DIG_Register DIG_Register_i32 (
    .D( s96 ),
    .C( CLK ),
    .en( s121 ),
    .Q( s122 )
  );
  DIG_Register DIG_Register_i33 (
    .D( s96 ),
    .C( CLK ),
    .en( s123 ),
    .Q( s124 )
  );
  DIG_Register DIG_Register_i34 (
    .D( s96 ),
    .C( CLK ),
    .en( s125 ),
    .Q( s126 )
  );
  DIG_Register DIG_Register_i35 (
    .D( s96 ),
    .C( CLK ),
    .en( s127 ),
    .Q( s128 )
  );
  Mux_16x1_NBits #(
    .Bits(16)
  )
  Mux_16x1_NBits_i36 (
    .sel( GPREG_OutSEL ),
    .in_0( s1 ),
    .in_1( s3 ),
    .in_2( s5 ),
    .in_3( s7 ),
    .in_4( s9 ),
    .in_5( s11 ),
    .in_6( s13 ),
    .in_7( s15 ),
    .in_8( s17 ),
    .in_9( s19 ),
    .in_10( s21 ),
    .in_11( s23 ),
    .in_12( s25 ),
    .in_13( s27 ),
    .in_14( s29 ),
    .in_15( s31 ),
    .out( GPREG_UOT )
  );
  assign s182[0] = s98;
  assign s182[1] = s100;
  assign s182[2] = s102;
  assign s182[3] = s104;
  assign s182[4] = s106;
  assign s182[5] = s108;
  assign s182[6] = s110;
  assign s182[7] = s112;
  assign s182[8] = s114;
  assign s182[9] = s116;
  assign s182[10] = s118;
  assign s182[11] = s120;
  assign s182[12] = s122;
  assign s182[13] = s124;
  assign s182[14] = s126;
  assign s182[15] = s128;
  assign s183[0] = (s80 | s182[0]);
  assign s183[1] = (s81 | s182[1]);
  assign s183[2] = (s82 | s182[2]);
  assign s183[3] = (s83 | s182[3]);
  assign s183[4] = (s84 | s182[4]);
  assign s183[5] = (s85 | s182[5]);
  assign s183[6] = (s86 | s182[6]);
  assign s183[7] = (s87 | s182[7]);
  assign s184[0] = (s88 | s182[8]);
  assign s184[1] = (s89 | s182[9]);
  assign s184[2] = (s90 | s182[10]);
  assign s184[3] = (s91 | s182[11]);
  assign s184[4] = (s92 | s182[12]);
  assign s184[5] = (s93 | s182[13]);
  assign s184[6] = (s94 | s182[14]);
  assign s184[7] = (s95 | s182[15]);
  assign s185 = ~ s182;
  assign s33 = s183[0];
  assign s36 = s183[1];
  assign s39 = s183[2];
  assign s42 = s183[3];
  assign s45 = s183[4];
  assign s48 = s183[5];
  assign s51 = s183[6];
  assign s54 = s183[7];
  assign s57 = s184[0];
  assign s60 = s184[1];
  assign s63 = s184[2];
  assign s66 = s184[3];
  assign s69 = s184[4];
  assign s72 = s184[5];
  assign s75 = s184[6];
  assign s78 = s184[7];
  assign s134 = s185[0];
  assign s137 = s185[1];
  assign s140 = s185[2];
  assign s143 = s185[3];
  assign s146 = s185[4];
  assign s149 = s185[5];
  assign s152 = s185[6];
  assign s155 = s185[7];
  assign s158 = s185[8];
  assign s161 = s185[9];
  assign s164 = s185[10];
  assign s167 = s185[11];
  assign s170 = s185[12];
  assign s173 = s185[13];
  assign s176 = s185[14];
  assign s179 = s185[15];
  Mux_2x1 Mux_2x1_i37 (
    .sel( s134 ),
    .in_0( s135 ),
    .in_1( GPIO_IN0x0 ),
    .out( s136 )
  );
  Mux_2x1 Mux_2x1_i38 (
    .sel( s137 ),
    .in_0( s138 ),
    .in_1( GPIO_IN0x1 ),
    .out( s139 )
  );
  Mux_2x1 Mux_2x1_i39 (
    .sel( s140 ),
    .in_0( s141 ),
    .in_1( GPIO_IN0x2 ),
    .out( s142 )
  );
  Mux_2x1 Mux_2x1_i40 (
    .sel( s143 ),
    .in_0( s144 ),
    .in_1( GPIO_IN0x3 ),
    .out( s145 )
  );
  Mux_2x1 Mux_2x1_i41 (
    .sel( s146 ),
    .in_0( s147 ),
    .in_1( GPIO_IN0x4 ),
    .out( s148 )
  );
  Mux_2x1 Mux_2x1_i42 (
    .sel( s149 ),
    .in_0( s150 ),
    .in_1( GPIO_IN0x5 ),
    .out( s151 )
  );
  Mux_2x1 Mux_2x1_i43 (
    .sel( s152 ),
    .in_0( s153 ),
    .in_1( GPIO_IN0x6 ),
    .out( s154 )
  );
  Mux_2x1 Mux_2x1_i44 (
    .sel( s155 ),
    .in_0( s156 ),
    .in_1( GPIO_IN0x7 ),
    .out( s157 )
  );
  Mux_2x1 Mux_2x1_i45 (
    .sel( s158 ),
    .in_0( s159 ),
    .in_1( GPIO_IN0x8 ),
    .out( s160 )
  );
  Mux_2x1 Mux_2x1_i46 (
    .sel( s161 ),
    .in_0( s162 ),
    .in_1( GPIO_IN0x9 ),
    .out( s163 )
  );
  Mux_2x1 Mux_2x1_i47 (
    .sel( s164 ),
    .in_0( s165 ),
    .in_1( GPIO_IN0xA ),
    .out( s166 )
  );
  Mux_2x1 Mux_2x1_i48 (
    .sel( s167 ),
    .in_0( s168 ),
    .in_1( GPIO_IN0xB ),
    .out( s169 )
  );
  Mux_2x1 Mux_2x1_i49 (
    .sel( s170 ),
    .in_0( s171 ),
    .in_1( GPIO_IN0xC ),
    .out( s172 )
  );
  Mux_2x1 Mux_2x1_i50 (
    .sel( s173 ),
    .in_0( s174 ),
    .in_1( GPIO_IN0xD ),
    .out( s175 )
  );
  Mux_2x1 Mux_2x1_i51 (
    .sel( s176 ),
    .in_0( s177 ),
    .in_1( GPIO_IN0xE ),
    .out( s178 )
  );
  Mux_2x1 Mux_2x1_i52 (
    .sel( s179 ),
    .in_0( s180 ),
    .in_1( GPIO_IN0xF ),
    .out( s181 )
  );
  assign s133[0] = s136;
  assign s133[1] = s139;
  assign s133[2] = s142;
  assign s133[3] = s145;
  assign s133[4] = s148;
  assign s133[5] = s151;
  assign s133[6] = s154;
  assign s133[7] = s157;
  assign s133[8] = s160;
  assign s133[9] = s163;
  assign s133[10] = s166;
  assign s133[11] = s169;
  assign s133[12] = s172;
  assign s133[13] = s175;
  assign s133[14] = s178;
  assign s133[15] = s181;
  assign s132 = s133[3:0];
  assign s131 = s133[7:4];
  assign s130 = s133[11:8];
  assign s129 = s133[15:12];
  assign s32 = s129[0];
  assign s35 = s129[1];
  assign s38 = s129[2];
  assign s41 = s129[3];
  assign s44 = s130[0];
  assign s47 = s130[1];
  assign s50 = s130[2];
  assign s53 = s130[3];
  assign s56 = s131[0];
  assign s59 = s131[1];
  assign s62 = s131[2];
  assign s65 = s131[3];
  assign s68 = s132[0];
  assign s71 = s132[1];
  assign s74 = s132[2];
  assign s77 = s132[3];
  DIG_Register DIG_Register_i53 (
    .D( s32 ),
    .C( CLK ),
    .en( s33 ),
    .Q( s34 )
  );
  DIG_Register DIG_Register_i54 (
    .D( s35 ),
    .C( CLK ),
    .en( s36 ),
    .Q( s37 )
  );
  DIG_Register DIG_Register_i55 (
    .D( s38 ),
    .C( CLK ),
    .en( s39 ),
    .Q( s40 )
  );
  DIG_Register DIG_Register_i56 (
    .D( s41 ),
    .C( CLK ),
    .en( s42 ),
    .Q( s43 )
  );
  DIG_Register DIG_Register_i57 (
    .D( s44 ),
    .C( CLK ),
    .en( s45 ),
    .Q( s46 )
  );
  DIG_Register DIG_Register_i58 (
    .D( s47 ),
    .C( CLK ),
    .en( s48 ),
    .Q( s49 )
  );
  DIG_Register DIG_Register_i59 (
    .D( s50 ),
    .C( CLK ),
    .en( s51 ),
    .Q( s52 )
  );
  DIG_Register DIG_Register_i60 (
    .D( s53 ),
    .C( CLK ),
    .en( s54 ),
    .Q( s55 )
  );
  DIG_Register DIG_Register_i61 (
    .D( s56 ),
    .C( CLK ),
    .en( s57 ),
    .Q( s58 )
  );
  DIG_Register DIG_Register_i62 (
    .D( s59 ),
    .C( CLK ),
    .en( s60 ),
    .Q( s61 )
  );
  DIG_Register DIG_Register_i63 (
    .D( s62 ),
    .C( CLK ),
    .en( s63 ),
    .Q( s64 )
  );
  DIG_Register DIG_Register_i64 (
    .D( s65 ),
    .C( CLK ),
    .en( s66 ),
    .Q( s67 )
  );
  DIG_Register DIG_Register_i65 (
    .D( s68 ),
    .C( CLK ),
    .en( s69 ),
    .Q( s70 )
  );
  DIG_Register DIG_Register_i66 (
    .D( s71 ),
    .C( CLK ),
    .en( s72 ),
    .Q( s73 )
  );
  DIG_Register DIG_Register_i67 (
    .D( s74 ),
    .C( CLK ),
    .en( s75 ),
    .Q( s76 )
  );
  DIG_Register DIG_Register_i68 (
    .D( s77 ),
    .C( CLK ),
    .en( s78 ),
    .Q( s79 )
  );
  Mux_16x1 Mux_16x1_i69 (
    .sel( IO_OutSel ),
    .in_0( s34 ),
    .in_1( s37 ),
    .in_2( s40 ),
    .in_3( s43 ),
    .in_4( s46 ),
    .in_5( s49 ),
    .in_6( s52 ),
    .in_7( s55 ),
    .in_8( s58 ),
    .in_9( s61 ),
    .in_10( s64 ),
    .in_11( s67 ),
    .in_12( s70 ),
    .in_13( s73 ),
    .in_14( s76 ),
    .in_15( s79 ),
    .out( GPIO_DataOUT )
  );
  assign GPIO_OUT0x0 = (s34 & s98);
  assign GPIO_OUT0x1 = (s37 & s100);
  assign GPIO_OUT0x2 = (s40 & s102);
  assign GPIO_OUT0x3 = (s43 & s104);
  assign GPIO_OUT0x4 = (s46 & s106);
  assign GPIO_OUT0x5 = (s49 & s108);
  assign GPIO_OUT0x6 = (s52 & s110);
  assign GPIO_OUT0x7 = (s55 & s112);
  assign GPIO_OUT0x8 = (s58 & s114);
  assign GPIO_OUT0x9 = (s61 & s116);
  assign GPIO_OUT0xA = (s64 & s118);
  assign GPIO_OUT0xB = (s67 & s120);
  assign GPIO_OUT0xC = (s70 & s122);
  assign GPIO_OUT0xD = (s73 & s124);
  assign GPIO_OUT0xE = (s76 & s126);
  assign GPIO_OUT0xF = (s79 & s128);
endmodule
