/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */

module Decoder4 (
    output out_0,
    output out_1,
    output out_2,
    output out_3,
    output out_4,
    output out_5,
    output out_6,
    output out_7,
    output out_8,
    output out_9,
    output out_10,
    output out_11,
    output out_12,
    output out_13,
    output out_14,
    output out_15,
    input [3:0] sel
);
    assign out_0 = (sel == 4'h0)? 1'b1 : 1'b0;
    assign out_1 = (sel == 4'h1)? 1'b1 : 1'b0;
    assign out_2 = (sel == 4'h2)? 1'b1 : 1'b0;
    assign out_3 = (sel == 4'h3)? 1'b1 : 1'b0;
    assign out_4 = (sel == 4'h4)? 1'b1 : 1'b0;
    assign out_5 = (sel == 4'h5)? 1'b1 : 1'b0;
    assign out_6 = (sel == 4'h6)? 1'b1 : 1'b0;
    assign out_7 = (sel == 4'h7)? 1'b1 : 1'b0;
    assign out_8 = (sel == 4'h8)? 1'b1 : 1'b0;
    assign out_9 = (sel == 4'h9)? 1'b1 : 1'b0;
    assign out_10 = (sel == 4'ha)? 1'b1 : 1'b0;
    assign out_11 = (sel == 4'hb)? 1'b1 : 1'b0;
    assign out_12 = (sel == 4'hc)? 1'b1 : 1'b0;
    assign out_13 = (sel == 4'hd)? 1'b1 : 1'b0;
    assign out_14 = (sel == 4'he)? 1'b1 : 1'b0;
    assign out_15 = (sel == 4'hf)? 1'b1 : 1'b0;
endmodule

module DIG_BlockRAMDualPort
#(
    parameter Bits = 8,
    parameter AddrBits = 4
)
(
  input [(AddrBits-1):0] A,
  input [(Bits-1):0] Din,
  input str,
  input C,
  output [(Bits-1):0] D
);
  reg [(Bits-1):0] memory[0:((1 << AddrBits) - 1)];
  reg [(Bits-1):0] wData;

  assign D = wData;

  always @ (posedge C) begin
    wData <= memory[A];
    if (str)
      memory[A] <= Din;
  end
endmodule


module ALU_RegRST (
  input [15:0] D,
  input RST,
  output [15:0] Q
);
  wire s0;
  assign s0 = ~ RST;
  assign Q[0] = (s0 & D[0]);
  assign Q[1] = (s0 & D[1]);
  assign Q[2] = (s0 & D[2]);
  assign Q[3] = (s0 & D[3]);
  assign Q[4] = (s0 & D[4]);
  assign Q[5] = (s0 & D[5]);
  assign Q[6] = (s0 & D[6]);
  assign Q[7] = (s0 & D[7]);
  assign Q[8] = (s0 & D[8]);
  assign Q[9] = (s0 & D[9]);
  assign Q[10] = (s0 & D[10]);
  assign Q[11] = (s0 & D[11]);
  assign Q[12] = (s0 & D[12]);
  assign Q[13] = (s0 & D[13]);
  assign Q[14] = (s0 & D[14]);
  assign Q[15] = (s0 & D[15]);
endmodule

module DIG_Register_BUS #(
    parameter Bits = 1
)
(
    input C,
    input en,
    input [(Bits - 1):0]D,
    output [(Bits - 1):0]Q
);

    reg [(Bits - 1):0] state = 'h0;

    assign Q = state;

    always @ (posedge C) begin
        if (en)
            state <= D;
   end
endmodule

module \256bits_regRst  (
  input [63:0] D0,
  input [63:0] D1,
  input [63:0] D2,
  input [63:0] D3,
  input RST,
  output [15:0] Q0,
  output [15:0] Q1,
  output [15:0] Q2,
  output [15:0] Q3,
  output [15:0] Q4,
  output [15:0] Q5,
  output [15:0] Q6,
  output [15:0] Q7,
  output [15:0] Q8,
  output [15:0] Q9,
  output [15:0] Q10,
  output [15:0] Q11,
  output [15:0] Q12,
  output [15:0] Q13,
  output [15:0] Q14,
  output [15:0] Q15
);
  wire [15:0] s0;
  wire [15:0] s1;
  wire [15:0] s2;
  wire [15:0] s3;
  wire [15:0] s4;
  wire [15:0] s5;
  wire [15:0] s6;
  wire [15:0] s7;
  wire [15:0] s8;
  wire [15:0] s9;
  wire [15:0] s10;
  wire [15:0] s11;
  wire [15:0] s12;
  wire [15:0] s13;
  wire [15:0] s14;
  wire [15:0] s15;
  assign s0 = D0[15:0];
  assign s1 = D0[31:16];
  assign s2 = D0[47:32];
  assign s3 = D0[63:48];
  assign s4 = D1[15:0];
  assign s5 = D1[31:16];
  assign s6 = D1[47:32];
  assign s7 = D1[63:48];
  assign s8 = D2[15:0];
  assign s9 = D2[31:16];
  assign s10 = D2[47:32];
  assign s11 = D2[63:48];
  assign s12 = D3[15:0];
  assign s13 = D3[31:16];
  assign s14 = D3[47:32];
  assign s15 = D3[63:48];
  ALU_RegRST ALU_RegRST_i0 (
    .D( s0 ),
    .RST( RST ),
    .Q( Q0 )
  );
  ALU_RegRST ALU_RegRST_i1 (
    .D( s1 ),
    .RST( RST ),
    .Q( Q1 )
  );
  ALU_RegRST ALU_RegRST_i2 (
    .D( s2 ),
    .RST( RST ),
    .Q( Q2 )
  );
  ALU_RegRST ALU_RegRST_i3 (
    .D( s3 ),
    .RST( RST ),
    .Q( Q3 )
  );
  ALU_RegRST ALU_RegRST_i4 (
    .D( s4 ),
    .RST( RST ),
    .Q( Q4 )
  );
  ALU_RegRST ALU_RegRST_i5 (
    .D( s5 ),
    .RST( RST ),
    .Q( Q5 )
  );
  ALU_RegRST ALU_RegRST_i6 (
    .D( s6 ),
    .RST( RST ),
    .Q( Q6 )
  );
  ALU_RegRST ALU_RegRST_i7 (
    .D( s7 ),
    .RST( RST ),
    .Q( Q7 )
  );
  ALU_RegRST ALU_RegRST_i8 (
    .D( s8 ),
    .RST( RST ),
    .Q( Q8 )
  );
  ALU_RegRST ALU_RegRST_i9 (
    .D( s9 ),
    .RST( RST ),
    .Q( Q9 )
  );
  ALU_RegRST ALU_RegRST_i10 (
    .D( s10 ),
    .RST( RST ),
    .Q( Q10 )
  );
  ALU_RegRST ALU_RegRST_i11 (
    .D( s11 ),
    .RST( RST ),
    .Q( Q11 )
  );
  ALU_RegRST ALU_RegRST_i12 (
    .D( s12 ),
    .RST( RST ),
    .Q( Q12 )
  );
  ALU_RegRST ALU_RegRST_i13 (
    .D( s13 ),
    .RST( RST ),
    .Q( Q13 )
  );
  ALU_RegRST ALU_RegRST_i14 (
    .D( s14 ),
    .RST( RST ),
    .Q( Q14 )
  );
  ALU_RegRST ALU_RegRST_i15 (
    .D( s15 ),
    .RST( RST ),
    .Q( Q15 )
  );
endmodule

module Mux_16x1_NBits #(
    parameter Bits = 2
)
(
    input [3:0] sel,
    input [(Bits - 1):0] in_0,
    input [(Bits - 1):0] in_1,
    input [(Bits - 1):0] in_2,
    input [(Bits - 1):0] in_3,
    input [(Bits - 1):0] in_4,
    input [(Bits - 1):0] in_5,
    input [(Bits - 1):0] in_6,
    input [(Bits - 1):0] in_7,
    input [(Bits - 1):0] in_8,
    input [(Bits - 1):0] in_9,
    input [(Bits - 1):0] in_10,
    input [(Bits - 1):0] in_11,
    input [(Bits - 1):0] in_12,
    input [(Bits - 1):0] in_13,
    input [(Bits - 1):0] in_14,
    input [(Bits - 1):0] in_15,
    output reg [(Bits - 1):0] out
);
    always @ (*) begin
        case (sel)
            4'h0: out = in_0;
            4'h1: out = in_1;
            4'h2: out = in_2;
            4'h3: out = in_3;
            4'h4: out = in_4;
            4'h5: out = in_5;
            4'h6: out = in_6;
            4'h7: out = in_7;
            4'h8: out = in_8;
            4'h9: out = in_9;
            4'ha: out = in_10;
            4'hb: out = in_11;
            4'hc: out = in_12;
            4'hd: out = in_13;
            4'he: out = in_14;
            4'hf: out = in_15;
            default:
                out = 'h0;
        endcase
    end
endmodule


module RegisterFile (
  input CLK,
  input [15:0] D,
  input WE,
  input [7:0] ADDR,
  input SEL_BRAM,
  output [15:0] Data_Read
);
  wire s0;
  wire [15:0] s1;
  wire s2;
  wire [15:0] s3;
  wire s4;
  wire [15:0] s5;
  wire s6;
  wire [15:0] s7;
  wire s8;
  wire [15:0] s9;
  wire s10;
  wire [15:0] s11;
  wire s12;
  wire [15:0] s13;
  wire s14;
  wire [15:0] s15;
  wire s16;
  wire [15:0] s17;
  wire s18;
  wire [15:0] s19;
  wire s20;
  wire [15:0] s21;
  wire s22;
  wire [15:0] s23;
  wire s24;
  wire [15:0] s25;
  wire s26;
  wire [15:0] s27;
  wire s28;
  wire [15:0] s29;
  wire s30;
  wire [15:0] s31;
  wire [3:0] s32;
  wire s33;
  wire s34;
  wire s35;
  wire s36;
  wire s37;
  wire s38;
  wire s39;
  wire s40;
  wire s41;
  wire s42;
  wire s43;
  wire s44;
  wire s45;
  wire s46;
  wire s47;
  wire s48;
  wire [15:0] s49;
  wire [15:0] s50;
  wire [15:0] s51;
  wire [15:0] s52;
  wire [15:0] s53;
  wire [15:0] s54;
  wire [15:0] s55;
  wire [15:0] s56;
  wire [15:0] s57;
  wire [15:0] s58;
  wire [15:0] s59;
  wire [15:0] s60;
  wire [15:0] s61;
  wire [15:0] s62;
  wire [15:0] s63;
  wire [15:0] s64;
  wire [15:0] s65;
  wire s66;
  wire [15:0] s67;
  wire [15:0] s68;
  wire s69;
  wire [15:0] s70;
  wire [63:0] s71;
  wire s72;
  wire [63:0] s73;
  wire [63:0] s74;
  wire [63:0] s75;
  wire [15:0] s76;
  wire [15:0] s77;
  wire s78;
  assign s66 = (WE & SEL_BRAM);
  assign s72 = (~ SEL_BRAM & WE);
  assign s78 = ~ SEL_BRAM;
  assign s32 = ADDR[3:0];
  Decoder4 Decoder4_i0 (
    .sel( s32 ),
    .out_0( s33 ),
    .out_1( s34 ),
    .out_2( s35 ),
    .out_3( s36 ),
    .out_4( s37 ),
    .out_5( s38 ),
    .out_6( s39 ),
    .out_7( s40 ),
    .out_8( s41 ),
    .out_9( s42 ),
    .out_10( s43 ),
    .out_11( s44 ),
    .out_12( s45 ),
    .out_13( s46 ),
    .out_14( s47 ),
    .out_15( s48 )
  );
  DIG_BlockRAMDualPort #(
    .Bits(16),
    .AddrBits(8)
  )
  DIG_BlockRAMDualPort_i1 (
    .A( ADDR ),
    .Din( D ),
    .str( s66 ),
    .C( CLK ),
    .D( s67 )
  );
  assign s69 = ~ s72;
  assign s68[0] = s33;
  assign s68[1] = s34;
  assign s68[2] = s35;
  assign s68[3] = s36;
  assign s68[4] = s37;
  assign s68[5] = s38;
  assign s68[6] = s39;
  assign s68[7] = s40;
  assign s68[8] = s41;
  assign s68[9] = s42;
  assign s68[10] = s43;
  assign s68[11] = s44;
  assign s68[12] = s45;
  assign s68[13] = s46;
  assign s68[14] = s47;
  assign s68[15] = s48;
  ALU_RegRST ALU_RegRST_i2 (
    .D( s67 ),
    .RST( s78 ),
    .Q( s77 )
  );
  ALU_RegRST ALU_RegRST_i3 (
    .D( s68 ),
    .RST( s69 ),
    .Q( s70 )
  );
  assign s0 = s70[0];
  assign s2 = s70[1];
  assign s4 = s70[2];
  assign s6 = s70[3];
  assign s8 = s70[4];
  assign s10 = s70[5];
  assign s12 = s70[6];
  assign s14 = s70[7];
  assign s16 = s70[8];
  assign s18 = s70[9];
  assign s20 = s70[10];
  assign s22 = s70[11];
  assign s24 = s70[12];
  assign s26 = s70[13];
  assign s28 = s70[14];
  assign s30 = s70[15];
  DIG_Register_BUS #(
    .Bits(16)
  )
  DIG_Register_BUS_i4 (
    .D( D ),
    .C( CLK ),
    .en( s0 ),
    .Q( s1 )
  );
  DIG_Register_BUS #(
    .Bits(16)
  )
  DIG_Register_BUS_i5 (
    .D( D ),
    .C( CLK ),
    .en( s2 ),
    .Q( s3 )
  );
  DIG_Register_BUS #(
    .Bits(16)
  )
  DIG_Register_BUS_i6 (
    .D( D ),
    .C( CLK ),
    .en( s4 ),
    .Q( s5 )
  );
  DIG_Register_BUS #(
    .Bits(16)
  )
  DIG_Register_BUS_i7 (
    .D( D ),
    .C( CLK ),
    .en( s6 ),
    .Q( s7 )
  );
  DIG_Register_BUS #(
    .Bits(16)
  )
  DIG_Register_BUS_i8 (
    .D( D ),
    .C( CLK ),
    .en( s8 ),
    .Q( s9 )
  );
  DIG_Register_BUS #(
    .Bits(16)
  )
  DIG_Register_BUS_i9 (
    .D( D ),
    .C( CLK ),
    .en( s10 ),
    .Q( s11 )
  );
  DIG_Register_BUS #(
    .Bits(16)
  )
  DIG_Register_BUS_i10 (
    .D( D ),
    .C( CLK ),
    .en( s12 ),
    .Q( s13 )
  );
  DIG_Register_BUS #(
    .Bits(16)
  )
  DIG_Register_BUS_i11 (
    .D( D ),
    .C( CLK ),
    .en( s14 ),
    .Q( s15 )
  );
  DIG_Register_BUS #(
    .Bits(16)
  )
  DIG_Register_BUS_i12 (
    .D( D ),
    .C( CLK ),
    .en( s16 ),
    .Q( s17 )
  );
  DIG_Register_BUS #(
    .Bits(16)
  )
  DIG_Register_BUS_i13 (
    .D( D ),
    .C( CLK ),
    .en( s18 ),
    .Q( s19 )
  );
  DIG_Register_BUS #(
    .Bits(16)
  )
  DIG_Register_BUS_i14 (
    .D( D ),
    .C( CLK ),
    .en( s20 ),
    .Q( s21 )
  );
  DIG_Register_BUS #(
    .Bits(16)
  )
  DIG_Register_BUS_i15 (
    .D( D ),
    .C( CLK ),
    .en( s22 ),
    .Q( s23 )
  );
  DIG_Register_BUS #(
    .Bits(16)
  )
  DIG_Register_BUS_i16 (
    .D( D ),
    .C( CLK ),
    .en( s24 ),
    .Q( s25 )
  );
  DIG_Register_BUS #(
    .Bits(16)
  )
  DIG_Register_BUS_i17 (
    .D( D ),
    .C( CLK ),
    .en( s26 ),
    .Q( s27 )
  );
  DIG_Register_BUS #(
    .Bits(16)
  )
  DIG_Register_BUS_i18 (
    .D( D ),
    .C( CLK ),
    .en( s28 ),
    .Q( s29 )
  );
  DIG_Register_BUS #(
    .Bits(16)
  )
  DIG_Register_BUS_i19 (
    .D( D ),
    .C( CLK ),
    .en( s30 ),
    .Q( s31 )
  );
  assign s71[15:0] = s1;
  assign s71[31:16] = s3;
  assign s71[47:32] = s5;
  assign s71[63:48] = s7;
  assign s73[15:0] = s9;
  assign s73[31:16] = s11;
  assign s73[47:32] = s13;
  assign s73[63:48] = s15;
  assign s74[15:0] = s17;
  assign s74[31:16] = s19;
  assign s74[47:32] = s21;
  assign s74[63:48] = s23;
  assign s75[15:0] = s25;
  assign s75[31:16] = s27;
  assign s75[47:32] = s29;
  assign s75[63:48] = s31;
  \256bits_regRst  \256bits_regRst_i20 (
    .D0( s71 ),
    .D1( s73 ),
    .D2( s74 ),
    .D3( s75 ),
    .RST( s72 ),
    .Q0( s49 ),
    .Q1( s50 ),
    .Q2( s51 ),
    .Q3( s52 ),
    .Q4( s53 ),
    .Q5( s54 ),
    .Q6( s55 ),
    .Q7( s56 ),
    .Q8( s57 ),
    .Q9( s58 ),
    .Q10( s59 ),
    .Q11( s60 ),
    .Q12( s61 ),
    .Q13( s62 ),
    .Q14( s63 ),
    .Q15( s64 )
  );
  Mux_16x1_NBits #(
    .Bits(16)
  )
  Mux_16x1_NBits_i21 (
    .sel( s32 ),
    .in_0( s49 ),
    .in_1( s50 ),
    .in_2( s51 ),
    .in_3( s52 ),
    .in_4( s53 ),
    .in_5( s54 ),
    .in_6( s55 ),
    .in_7( s56 ),
    .in_8( s57 ),
    .in_9( s58 ),
    .in_10( s59 ),
    .in_11( s60 ),
    .in_12( s61 ),
    .in_13( s62 ),
    .in_14( s63 ),
    .in_15( s64 ),
    .out( s65 )
  );
  ALU_RegRST ALU_RegRST_i22 (
    .D( s65 ),
    .RST( SEL_BRAM ),
    .Q( s76 )
  );
  assign Data_Read = (s76 | s77);
endmodule
